<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Order Status_fa fa-pencil</name>
   <tag></tag>
   <elementGuidId>33991496-b89e-4dbb-b9ba-7a1cf645335e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-pencil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='1137']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3c307301-158e-4f30-80b0-ab42cff6ece2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-pencil</value>
      <webElementGuid>122416bb-8bec-4411-bb67-090f87837a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblListData&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[1]/div[@class=&quot;btn-group&quot;]/a[@id=&quot;1137&quot;]/i[@class=&quot;fa fa-pencil&quot;]</value>
      <webElementGuid>863e5657-5436-47a8-97a8-65e9275b9f7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='1137']/i</value>
      <webElementGuid>8e279e69-9812-4713-9c25-37b87f0db406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/i</value>
      <webElementGuid>e9440907-9feb-443e-b0e7-bb3cf945a1a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
