<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a4976c7f-3d9e-494d-8e45-9a7af7fcd465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Click here to add new product&quot;] > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='product']/thead/tr/th[6]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>235f0b3b-106a-4264-a8a4-e5c115172227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/admin/themes/admin_panel/dist/img/plus.png</value>
      <webElementGuid>37ee4e2a-4997-4095-8500-0ed483c0f693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product&quot;)/thead[1]/tr[1]/th[6]/a[1]/img[1]</value>
      <webElementGuid>5af4f515-0581-4c08-8d57-2670c98d08b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='product']/thead/tr/th[6]/a/img</value>
      <webElementGuid>03711e48-ca47-4c29-bf67-9e58ba8a12e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev.thcitsolutions.com/vrajfresh/admin/themes/admin_panel/dist/img/plus.png')]</value>
      <webElementGuid>9e5f5c4b-5699-425d-ab88-8133dafae345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/a/img</value>
      <webElementGuid>fcb2a74c-b9d0-45c9-946f-0d795fe6f7ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.thcitsolutions.com/vrajfresh/admin/themes/admin_panel/dist/img/plus.png']</value>
      <webElementGuid>9d2a3d55-213e-432a-9372-8b6157a4e05c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
