<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PAGE IS LOADING_txtSearchKeyWord</name>
   <tag></tag>
   <elementGuidId>2af121e5-a39c-4d17-ad8d-a7f4056f7914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSearchKeyWord</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmListDataFilter']/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a021c65e-0f90-4db3-9068-77cbda5df92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>bf9d349e-fdb1-41a7-9de3-42dcd0cf4089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9be8482d-79b8-431b-beb2-fc944017e920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>extra_field form-control</value>
      <webElementGuid>410b13bb-637a-42de-ba19-3159b1ddf6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtSearchKeyWord</value>
      <webElementGuid>4ba0d2a6-ee29-49f4-b3a2-ebfeab16e3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSearchKeyWord</value>
      <webElementGuid>ad095bde-4dc2-4a4f-a958-3745de6841b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Keyword</value>
      <webElementGuid>efb6e92d-5d57-41d8-98c8-4960d00a664c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSearchKeyWord&quot;)</value>
      <webElementGuid>5f903b4c-1490-4a8b-914f-0d6f1d2d356a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSearchKeyWord']</value>
      <webElementGuid>7531ef97-32c0-405f-82a6-43a986d50b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmListDataFilter']/div/input</value>
      <webElementGuid>efaa0fe8-9f2c-4d94-ae10-b0e91579a21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c4c8da0a-44bb-4c11-b43b-35bbb6f058da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txtSearchKeyWord' and @id = 'txtSearchKeyWord' and @placeholder = 'Search Keyword']</value>
      <webElementGuid>badcf096-aedd-41d1-93af-e084fed0e446</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
