<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kinder Joy (20g  0.7Oz)_qty3620</name>
   <tag></tag>
   <elementGuidId>0f356b73-886f-441b-8549-34f6dd6ce903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qty3620</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qty3620']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce23bbc6-1f00-4b81-82d3-1181897c92e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63300c9b-3a7d-46a3-8ad7-880a9f39805b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>QTY</value>
      <webElementGuid>146f67e6-e993-49cb-b408-188c4ee5b165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control qty</value>
      <webElementGuid>7f225567-cb8a-4194-ae2f-0f47323038ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qty3620</value>
      <webElementGuid>5e05aec3-a665-4705-b4b1-25f1d2be5b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>qty[3620]</value>
      <webElementGuid>68b3f9a8-5518-4bae-a97c-452d022ed066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7a4b07aa-dfb5-4876-8bd6-240469d49aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateProductTotalAmount(this.value,3620);</value>
      <webElementGuid>6c40e7a5-be6b-4341-93b8-0de8017ec74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qty3620&quot;)</value>
      <webElementGuid>3159493c-6d22-4016-bdc2-d252650a8813</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qty3620']</value>
      <webElementGuid>b835f3d7-d165-4491-ab3b-b4b87e7b1fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='product']/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>ab6a28aa-fe27-4928-92d5-e38c64eefab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>0e394645-fff4-4335-98b6-fd350a111f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'QTY' and @id = 'qty3620' and @name = 'qty[3620]']</value>
      <webElementGuid>72682bdc-dbc4-4251-8802-596469185346</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
