<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Order Discount_discount_amount</name>
   <tag></tag>
   <elementGuidId>670df319-aca4-4272-a316-7962b55aa12a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#discount_amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='discount_amount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9c9e55c-bc5d-4be1-9405-4807d9d60b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4761632a-3414-442c-826a-7fd70ea66bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Order Discount</value>
      <webElementGuid>a8906a6f-f174-4e84-9fda-692893a17fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9d620961-b3c2-4083-a3f9-a11c85677ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>discount_amount</value>
      <webElementGuid>47dd9cd0-a7b8-4940-ac5d-23bc48d16928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>discount_amount</value>
      <webElementGuid>907dd15f-2e4c-469b-9392-23b63cd569cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>20.00</value>
      <webElementGuid>93c9ed36-0ec4-4664-9040-62a8fc8e5948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateFooterTotal();</value>
      <webElementGuid>102f596d-6422-4745-9e37-716c60cfdd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;discount_amount&quot;)</value>
      <webElementGuid>a3a71039-256b-440d-90fb-6521aab71b6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='discount_amount']</value>
      <webElementGuid>b62bd117-8283-4311-b36d-82bfdea0721e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='banner_frm']/div[4]/div[3]/input</value>
      <webElementGuid>775433e2-f6d3-440e-899e-26559054769d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/input</value>
      <webElementGuid>a8a82604-2889-4814-a076-6ac67afe904b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Order Discount' and @name = 'discount_amount' and @id = 'discount_amount']</value>
      <webElementGuid>0a285fd5-4f0d-4c48-86d3-8afd473b42d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
