<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_38.29</name>
   <tag></tag>
   <elementGuidId>8023d8a2-d123-47ed-a071-e9ea63e14aa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#total_amount_final</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='total_amount_final']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a393e84b-a20d-4cd8-bd64-0b2b8999a504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>total_amount_final</value>
      <webElementGuid>66ed7422-0260-4e69-bf82-c1f3b06d3537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$
            38.29         </value>
      <webElementGuid>ee41899f-fa8d-4851-afb0-c1165745ec55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;total_amount_final&quot;)</value>
      <webElementGuid>7078a1db-b7c4-436a-9d80-da9fd557e7ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='total_amount_final']</value>
      <webElementGuid>5be5ec7d-9eb7-4ade-acbe-c0e3a1f85ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='banner_frm']/div/div[5]/label[2]</value>
      <webElementGuid>2864db31-62f0-4bc1-a208-771461b53388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Amount :'])[1]/following::label[1]</value>
      <webElementGuid>9e26ac2d-c670-4fa0-abcc-c0ad83c2d7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No, please refund for unavailable items'])[1]/following::label[2]</value>
      <webElementGuid>655f39be-0984-47c2-9852-ac9ff2633a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Products'])[1]/preceding::label[1]</value>
      <webElementGuid>0e3a31cf-d051-4c35-9966-a1f7c896691d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Name'])[1]/preceding::label[2]</value>
      <webElementGuid>f48ec914-317f-437f-97e0-471ff291da12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label[2]</value>
      <webElementGuid>1b9f0b12-baf7-4fd9-8881-894fe283433d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'total_amount_final' and (text() = '$
            38.29         ' or . = '$
            38.29         ')]</value>
      <webElementGuid>97786162-667f-4010-bd52-ccaa19f6c88f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
