<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Parle - s - 3 gms</name>
   <tag></tag>
   <elementGuidId>1090acc7-7123-4ad9-b83b-e9764c4c45a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-ArrNewProducts-kr-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-ArrNewProducts-kr-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>640f5041-ada7-4345-9650-84d06a14bce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>242a9b13-3b89-42f5-b196-a183c0277885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ArrNewProducts-kr-container</value>
      <webElementGuid>c1f93dc0-1366-4987-ab6d-7a42b0c3d9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>e578d61b-2ab3-4a83-a8de-cb4ab37acbd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d04ec7b0-560e-49b9-88ad-94d503262fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Parle - s - 3 gms</value>
      <webElementGuid>cac415fa-3b32-43c4-aaad-221e87c1f666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Parle - s - 3 gms</value>
      <webElementGuid>84c692ac-5ae7-47da-a9b8-e96015a22f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ArrNewProducts-kr-container&quot;)</value>
      <webElementGuid>02fa77f7-b530-4572-909b-4840fe2b5313</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-ArrNewProducts-kr-container']</value>
      <webElementGuid>0f5d712c-0405-4ab9-bdf7-9cad49465276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='product']/tr/td/span/span/span/span</value>
      <webElementGuid>fbb32ba0-155d-414d-b392-9318d7d82575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[2]/following::span[4]</value>
      <webElementGuid>5e0788d2-0679-4afa-9420-e7fcd39dcf31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[1]/following::span[4]</value>
      <webElementGuid>85fc4cea-7fbe-4669-b0f6-99b372fd69e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Charge :'])[1]/preceding::span[3]</value>
      <webElementGuid>a7727364-3456-4b56-b2dd-4b1f950e3bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tip Amount :'])[1]/preceding::span[3]</value>
      <webElementGuid>c3b00bab-d77e-4998-a84f-d8e761d3fc8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/span/span/span</value>
      <webElementGuid>cc1dc1df-64b9-4d5a-938b-dca996380e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-ArrNewProducts-kr-container' and @title = 'Parle - s - 3 gms' and (text() = 'Parle - s - 3 gms' or . = 'Parle - s - 3 gms')]</value>
      <webElementGuid>760c032e-5cee-4031-a73f-15cac2a4e607</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
