<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_36.30</name>
   <tag></tag>
   <elementGuidId>fb808fdd-204f-4944-a9d9-59a695c1fff7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transaction > tbody > tr > td:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='transaction']/tbody/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ccc44a2f-b8a4-4e74-857e-7cb1b291bee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>36.30</value>
      <webElementGuid>9bef43aa-24ef-4522-b0bd-ff1e98083124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transaction&quot;)/tbody[1]/tr[1]/td[4]</value>
      <webElementGuid>f6f572e1-7c28-43b8-907a-1c96fbb694fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='transaction']/tbody/tr/td[4]</value>
      <webElementGuid>b3513460-2f0d-4540-81b9-37be74905560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='requires_capture'])[1]/following::td[1]</value>
      <webElementGuid>e9249064-77f5-4008-bf05-d682ec0a1b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual'])[1]/following::td[2]</value>
      <webElementGuid>64f954c0-7e5c-4581-8997-fd440f9bac7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::td[2]</value>
      <webElementGuid>5d231059-c75e-4dac-b5c7-81bd544bbb9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::td[2]</value>
      <webElementGuid>3ff58076-fa3a-4c70-b16c-a91e3e7147d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b/div/div/div/div[2]/table/tbody/tr/td[4]</value>
      <webElementGuid>2bf785a1-f056-46f9-a8a3-74a484e6b169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '36.30' or . = '36.30')]</value>
      <webElementGuid>3069851f-67a9-479b-aa36-a81525a63630</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
