<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>11cea8bc-d2e0-4795-92d0-54d28f6a7147</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_6271</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_6271']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6a4f226f-1db6-4075-ba38-01876b7753f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_6271</value>
      <webElementGuid>7f94f722-4314-4a18-8460-24871e7a4a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add_cart </value>
      <webElementGuid>0f8493bd-0418-4c50-a0da-d22fb74bd30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isperisible</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>44552ec2-bd1e-48ce-9a78-33edc5122aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productslug</name>
      <type>Main</type>
      <value>kawan-flakey-paratha</value>
      <webElementGuid>18a0b522-91de-402c-a129-c9bfad3db0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productimage</name>
      <type>Main</type>
      <value>https://www.vrajfresh.com/admin/uploads/products/18169258-724E-44B2-A029-EC07C923400D.jpg</value>
      <webElementGuid>89e2f4c8-d0a5-4beb-8076-e19880aab33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productname</name>
      <type>Main</type>
      <value>Kawan Flakey Paratha</value>
      <webElementGuid>ac8144e7-8ee4-4805-b757-8bf2e39bc737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>3.99</value>
      <webElementGuid>358e1e8b-299b-409b-a3de-c55733660ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productid</name>
      <type>Main</type>
      <value>6271</value>
      <webElementGuid>9bddcf47-b2af-422a-82a8-2c448da7ab26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productweight</name>
      <type>Main</type>
      <value>5.00</value>
      <webElementGuid>749f3026-efaf-4f97-8cce-a1b754b16300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-producttax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>295be522-f049-4682-9c8a-009f3309fb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>39ab576d-8862-43db-83c5-fbf3482d9dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_6271&quot;)</value>
      <webElementGuid>e566792c-f60b-4946-bb8b-ad2306d7f66b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_6271']</value>
      <webElementGuid>623d1340-4523-457c-8b30-e148ffcb433b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_product']/div/div/ul/li[2]/button</value>
      <webElementGuid>a116019a-c9ca-4b59-89da-9726a272ad14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::button[1]</value>
      <webElementGuid>0f2bfe41-603d-43d3-8db0-29eba15aeae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::button[2]</value>
      <webElementGuid>2407ba7f-bf7b-426a-9beb-7f98cae7bf60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@vrajfresh.com'])[1]/preceding::button[1]</value>
      <webElementGuid>47ddcef5-5035-46bd-b612-b1a38394f3e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>a130daad-f84f-4e02-8419-62731c780216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[2]/button</value>
      <webElementGuid>b5c6121d-af75-44f9-8421-0e9255a55c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_6271' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>6e73061f-10a1-4fbb-9c93-c70a8b892d81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
