<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_5</name>
   <tag></tag>
   <elementGuidId>c94fa065-d83d-46ee-9e9b-05dfde595fd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order_tip_5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='order_tip_5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a3c75786-27b0-45a0-840c-1e6c835b87aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_tip_5</value>
      <webElementGuid>555ff679-7961-4149-b957-6b24ed86acff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5903cb46-ed4c-461b-a0c5-9bd8a70003d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order_tip</value>
      <webElementGuid>4065d49b-58c7-4783-b5af-93060b0468df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tip</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>7e5ad055-2221-4258-a760-0e64871290e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$5</value>
      <webElementGuid>c0107756-59ec-4598-a28d-d50d18049f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_tip_5&quot;)</value>
      <webElementGuid>d1bc3fbc-063f-4ad0-8279-bbc5871dff4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='order_tip_5']</value>
      <webElementGuid>a7b8b387-e794-4b3a-8660-0fc7fa0351a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/section/div/div/div[11]/button</value>
      <webElementGuid>5e5a2932-58fd-49f2-b73a-60d37d03bce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tip'])[1]/following::button[1]</value>
      <webElementGuid>25709903-fe4c-4ad7-ab7c-b9a1e35a579e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentitive Delivery Date:'])[1]/following::button[1]</value>
      <webElementGuid>e01f4287-c9e7-4b89-b305-2dca3e69fcbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 10'])[1]/preceding::button[1]</value>
      <webElementGuid>60a457f4-fd59-4b8e-b804-2120350e6dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 15'])[1]/preceding::button[2]</value>
      <webElementGuid>25aca2bb-e5d8-46c3-a1c0-d12aa7a95420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$5']/parent::*</value>
      <webElementGuid>e8d0274d-ef5f-4121-9447-3b0b1e491a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/button</value>
      <webElementGuid>b0c431dc-ce2a-4405-b306-88d151de8d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'order_tip_5' and @type = 'button' and (text() = '$5' or . = '$5')]</value>
      <webElementGuid>f87a89bd-5fcf-4821-9627-d7d7b888b8b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
