<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Custom Tip</name>
   <tag></tag>
   <elementGuidId>b2e807d8-2fdd-4a9b-bc5d-b20a3a49fc48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order_tip_custom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='order_tip_custom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8430feee-ac9c-47b1-b792-3122a25a6ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_tip_custom</value>
      <webElementGuid>f6b96a1b-0d38-4349-9fa2-e236088499ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>41c68a9e-55ff-44ec-b419-ac4f119a6af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>fa7ba43a-afae-4c47-956b-86fcec647894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tip</name>
      <type>Main</type>
      <value>custom</value>
      <webElementGuid>8badfda8-2376-4073-96b5-92d98c53ae88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addCustomTip();</value>
      <webElementGuid>4c7df8f0-0a5e-4f6c-9f5f-c8882cbc7bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Custom Tip </value>
      <webElementGuid>3f257f3c-6765-4cb0-87b1-ba0608ba0b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_tip_custom&quot;)</value>
      <webElementGuid>d43a66fd-12d2-449b-84dd-575c1b596036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='order_tip_custom']</value>
      <webElementGuid>ed141a03-80a5-4c6a-b13b-9de282f25931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/section/div/div/div[11]/button[6]</value>
      <webElementGuid>61179df0-5ba6-4d3a-a3bc-c948a0e61990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 25'])[1]/following::button[1]</value>
      <webElementGuid>9aa9f027-8da0-4a01-bba9-e45eb87e562a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 20'])[1]/following::button[2]</value>
      <webElementGuid>5a479536-5e83-4dcc-9dbb-ba220cc7e2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter valid amount'])[1]/preceding::button[1]</value>
      <webElementGuid>93a9dd26-bdff-418a-9147-bd8ab2b1b337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Tip'])[1]/preceding::button[1]</value>
      <webElementGuid>a24d5c9c-ca0a-47a2-b984-9987df7fbc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Custom Tip']/parent::*</value>
      <webElementGuid>d8a7dc85-0747-4875-a8ea-a38c7562042d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[6]</value>
      <webElementGuid>aa6aa99d-f0a7-44b2-a6ab-d9bdfe0f3aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'order_tip_custom' and @type = 'button' and (text() = 'Custom Tip ' or . = 'Custom Tip ')]</value>
      <webElementGuid>cc73daa1-0769-4eb7-b33f-4e2b757619a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
