<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shiping_street_address</name>
   <tag></tag>
   <elementGuidId>7db09ef9-76a3-482a-b571-9520999137ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shiping_street_address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shiping_street_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a87e26c-4841-4aad-9d13-830ef77e4874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>House number and street name</value>
      <webElementGuid>6d677df5-b58e-4d8e-9a0b-f9083ce2932e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6200 Winnetka Ave</value>
      <webElementGuid>90df5b1e-611a-45d2-ac83-1c426a44ab71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shiping_street_address</value>
      <webElementGuid>1f1c8710-51c5-4188-8f30-ca6dd831a399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shiping_street_address</value>
      <webElementGuid>28791f38-1f74-4ba8-bb7c-b935471ac17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ea79e2f-7077-47e8-b19d-54d01a916c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>fef58256-0702-493d-a876-f85116b2e885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shiping_street_address&quot;)</value>
      <webElementGuid>53d8b4c6-9da3-441c-b5cf-554a91f7301a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shiping_street_address']</value>
      <webElementGuid>262ad180-864f-4d91-950d-0dd0b3b1a467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipingAddressBox']/div/input</value>
      <webElementGuid>2ed2758a-15d3-4b09-b9ba-2f4c8e0fb55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>21bcedfd-dea0-4930-8779-38609736b5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'House number and street name' and @name = 'shiping_street_address' and @id = 'shiping_street_address' and @type = 'text']</value>
      <webElementGuid>e2d24522-ff39-484c-803d-69225886a962</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
