<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_43.9_zipcode</name>
   <tag></tag>
   <elementGuidId>8bcfe04e-3122-4a77-b2ba-e2d3d8321dec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zipcode_cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zipcode_cart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>227b4269-1504-41a6-9ff3-3ab9f9ed6141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>16d9485a-953a-4ee0-b63c-6381ec8d9459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>We deliver in your area</value>
      <webElementGuid>8b77e31e-61a6-4f8b-b716-312e9b7bbf25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4adf62fd-6867-4cb8-b85e-96dad81f280f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zipcode_cart</value>
      <webElementGuid>162a3179-7fd0-4333-bb01-2ba8b0228989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>d6a971f1-8594-4435-9798-3a5d4f79f2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>numberonly_cart</value>
      <webElementGuid>11bf97f9-c121-424e-a22d-94bfffc472ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zipcode_cart&quot;)</value>
      <webElementGuid>9048ac11-baae-4b41-9a67-dee46f365ed9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zipcode_cart']</value>
      <webElementGuid>9ccfc48d-de21-44dd-ba32-5a51c0fd9bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>81653e30-625f-4b91-8be6-fa86bb9a1331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'zipcode' and @placeholder = 'We deliver in your area' and @type = 'text' and @id = 'zipcode_cart']</value>
      <webElementGuid>99f8b6eb-526d-46e9-90a4-d91e2487794c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
