<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shiping_zip_code</name>
   <tag></tag>
   <elementGuidId>43e761ca-34d8-470d-9d1f-81974cd895fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shiping_zip_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec83d43b-7493-4246-9ea9-b7de726658c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip Code</value>
      <webElementGuid>d2ff8742-bf82-4bc8-adcb-316c81945d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shiping_zip_code</value>
      <webElementGuid>7b22d9fc-3549-4985-8733-2fc83acd4373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shiping_zip_code</value>
      <webElementGuid>9cba6b96-590c-4f5d-9cc1-4a24501a7aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14df28bd-9a56-4853-9db5-ac42f12f87c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>5ad7257d-16fc-4ca4-b69e-c95a886ad649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shiping_zip_code&quot;)</value>
      <webElementGuid>d459294e-69a1-4d0c-81c1-aa40c9e04143</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shiping_zip_code']</value>
      <webElementGuid>bc2de481-e310-4648-856c-18e84e79c929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipingAddressBox']/div[4]/input</value>
      <webElementGuid>48a4e474-6f9d-42ab-8e1b-e9eac6150ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[4]/input</value>
      <webElementGuid>e18c06d1-0e60-46ad-ba58-b6bdf7398419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Zip Code' and @name = 'shiping_zip_code' and @id = 'shiping_zip_code' and @type = 'text']</value>
      <webElementGuid>1af24f7d-8a76-493c-a677-96dbec94d4bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
