<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Capture Payment</name>
   <tag></tag>
   <elementGuidId>0bbe2a3b-425b-4770-b941-21e0a22b3198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='payBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3323aa17-5fef-4c08-a1a4-98c9974123de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5ce7701-e30f-46ee-a3a1-ff322471d9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payBtn</value>
      <webElementGuid>e0d81e53-a9e2-46a1-b09e-d659f447ad00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>2400be79-b795-40d4-acdd-0ff380807a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Capture Payment</value>
      <webElementGuid>601ff043-f928-4bdb-8b20-59487ed1e296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payBtn&quot;)</value>
      <webElementGuid>d23bab39-af18-4c7b-9196-cd994bb3ff01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='payBtn']</value>
      <webElementGuid>5a01cc73-9447-49bf-acd4-08daef3f930a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='paymentFrm']/div/div[2]/button</value>
      <webElementGuid>67a5ddc8-26fc-4770-93cf-06d94279f200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Order'])[1]/following::button[1]</value>
      <webElementGuid>79fe1ddd-2f89-4b52-be44-e9cf33fede08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Address :'])[1]/following::button[2]</value>
      <webElementGuid>0dcfda28-79b4-4763-96c1-efc7a5c6f84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transactions :'])[1]/preceding::button[1]</value>
      <webElementGuid>24ac7132-442b-44cb-986c-1a55e45f6b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction ID'])[1]/preceding::button[1]</value>
      <webElementGuid>f77679eb-33cd-41f2-bcd8-fdc4fb31bdbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Capture Payment']/parent::*</value>
      <webElementGuid>8a18ec2e-df0a-4380-8fd5-4a56f57a8389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>bb70fc05-1634-4c44-ad92-f6326a754b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'payBtn' and (text() = 'Capture Payment' or . = 'Capture Payment')]</value>
      <webElementGuid>7202ea03-70bc-436c-883f-2f150aee4b6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
