<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__searchSubmit</name>
   <tag></tag>
   <elementGuidId>f59fdd31-7dbd-448b-897a-b46aa1b6933b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e90f896d-d1af-474d-a040-e5415411d123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cc36b796-a6b2-4a10-9e2e-eb8ee6abc252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>5e4a6085-1ab2-4eac-b6fe-6f642853cf92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchSubmit</value>
      <webElementGuid>0d7546fd-8520-4c3d-91d0-dbd114f203e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchSubmit</value>
      <webElementGuid>6a4c7c6f-8ea5-405b-888a-7118a0d24ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>fd3fb18a-7c4b-4996-934c-1798b75a5b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchSubmit&quot;)</value>
      <webElementGuid>028affe3-c652-4cf6-9155-1b47ff698793</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchSubmit']</value>
      <webElementGuid>f53b28d3-ee8c-4bee-a4ef-13d71e170f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmListDataFilter']/div[5]/input</value>
      <webElementGuid>adcbe3ca-0146-452e-be89-6869a13cfc92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>88db91d4-f2bf-4fcc-a872-997de89989d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'searchSubmit' and @id = 'searchSubmit']</value>
      <webElementGuid>3c571b53-0f90-4f6f-a1b1-f7734e1dfa86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
