<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tip Amount_order_tip</name>
   <tag></tag>
   <elementGuidId>9268ac1e-cf33-49f8-8d30-9d9845711edb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order_tip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='order_tip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26c3027c-e416-447d-9c22-135fb2281b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7051885c-cbfc-4d47-9f4c-0b414bbb9100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Order Tip</value>
      <webElementGuid>b5c04570-9ced-49f1-a222-10057d25742d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b11264e7-ad39-4036-9417-bd2c4a539178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_tip</value>
      <webElementGuid>fa2b768d-41be-4443-a1ce-ce8c9f78ddcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_tip</value>
      <webElementGuid>4d77f1df-c214-4192-ade9-08600a8c4125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10.00</value>
      <webElementGuid>84159100-e0ed-469c-bdf3-f5654fc27e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateFooterTotal();</value>
      <webElementGuid>09121e12-f0cc-4215-aa28-fbdea4824b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_tip&quot;)</value>
      <webElementGuid>61f61c7f-b295-4b13-81d7-843670f9b070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='order_tip']</value>
      <webElementGuid>cfbe2640-7df9-474b-8f4e-b9d04ad2775d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='banner_frm']/div[4]/div[2]/input</value>
      <webElementGuid>2e81f4d6-462e-4ef6-9bc7-cffda7d680ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>ec435bfc-a168-4b47-a00b-c428507c69bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Order Tip' and @name = 'order_tip' and @id = 'order_tip']</value>
      <webElementGuid>a450c879-546e-44e5-9121-1353b9b7fde1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
