<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_36.30</name>
   <tag></tag>
   <elementGuidId>1855157a-6694-42c7-b15e-aeb1a8da507f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#total_amount_final</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='total_amount_final']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>42c09f45-1659-401b-9f9f-c3af02cae735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>total_amount_final</value>
      <webElementGuid>690b1dc9-4dab-4fc4-8544-911bec2d6695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$
            36.30         </value>
      <webElementGuid>0822ed0d-61d8-4f6c-9e77-d97584b03068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;total_amount_final&quot;)</value>
      <webElementGuid>b67ff1d4-d0dd-4246-88ce-326b59020c0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='total_amount_final']</value>
      <webElementGuid>009c9a47-0a5a-4235-bdcc-89b31aa62d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='banner_frm']/div/div[5]/label[2]</value>
      <webElementGuid>9eba5f73-8db3-4b49-8896-416312c1d28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Amount :'])[1]/following::label[1]</value>
      <webElementGuid>6353ecb8-5ceb-488b-ac1c-645260130e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No, please refund for unavailable items'])[1]/following::label[2]</value>
      <webElementGuid>626709b0-3fc8-43cd-bd86-2f6d6ed9f937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Products'])[1]/preceding::label[1]</value>
      <webElementGuid>5c9e0d26-5ffc-4776-b1bc-d7d99361b323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Name'])[1]/preceding::label[2]</value>
      <webElementGuid>7d2b4051-9cfe-4822-8758-e35d6383249c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label[2]</value>
      <webElementGuid>478064de-812b-4192-8927-d3f04669e35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'total_amount_final' and (text() = '$
            36.30         ' or . = '$
            36.30         ')]</value>
      <webElementGuid>8ff3d1a0-346b-4c57-b072-1233d8ff1b0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
