<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_36.30</name>
   <tag></tag>
   <elementGuidId>ae712af8-c775-4f3f-a4c0-ac52cb7b0d65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#labelOrderAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='total_amount_final']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>51d8d678-f780-46dc-b68f-b73fa60ee3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>labelOrderAmount</value>
      <webElementGuid>9f568abf-eb04-4408-85c0-8777ecde6cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>36.30</value>
      <webElementGuid>03e62441-502a-4b72-a623-cb12277aa838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;labelOrderAmount&quot;)</value>
      <webElementGuid>49412c6d-adc3-44fb-8056-4917dabe69a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='labelOrderAmount']</value>
      <webElementGuid>6aaf0d9d-199b-439f-aedb-9e003b3c444e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='banner_frm']/div/div[3]/label[2]/span</value>
      <webElementGuid>ccf07837-29b2-4251-8744-8f569f65ba8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Amount :'])[1]/following::span[1]</value>
      <webElementGuid>b12bef9d-0587-4156-b364-39e6ef33fd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No, please refund for unavailable items'])[1]/preceding::span[1]</value>
      <webElementGuid>36f10684-38e7-4f1d-b8b0-8499b9c22be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Amount :'])[1]/preceding::span[1]</value>
      <webElementGuid>07fe640e-9449-46d8-b772-04cb425b5419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span</value>
      <webElementGuid>deb61245-ea76-425d-9018-b216644514ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'labelOrderAmount' and (text() = '36.30' or . = '36.30')]</value>
      <webElementGuid>f28a21da-99fa-49c2-8af9-0209b3fff5c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
