<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_38.29</name>
   <tag></tag>
   <elementGuidId>05ed3eab-49b9-48d6-9840-8d80cbe0a2b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#labelOrderAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='labelOrderAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3aed141d-e8ae-44d6-b80c-6ab8c8c40f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>labelOrderAmount</value>
      <webElementGuid>de4d00a9-1fae-4b6b-a062-f17b7a3d31d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>38.29</value>
      <webElementGuid>3eda1fb9-af82-4d8e-949f-e899452d33b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;labelOrderAmount&quot;)</value>
      <webElementGuid>1e336078-749e-49bb-87b5-850e9b7b5774</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='labelOrderAmount']</value>
      <webElementGuid>e4306359-55e5-45e4-8dbb-d20df313ca49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='banner_frm']/div/div[3]/label[2]/span</value>
      <webElementGuid>9ce6d8a0-814b-4479-981e-eac35c2b9587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Amount :'])[1]/following::span[1]</value>
      <webElementGuid>de2204f6-10c5-4bc1-8f27-55b92b4dbbe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No, please refund for unavailable items'])[1]/preceding::span[1]</value>
      <webElementGuid>d209b413-1844-4db2-aa44-9968bc301ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Amount :'])[1]/preceding::span[1]</value>
      <webElementGuid>d613cc0a-21d7-41ef-aa83-84585d2c1fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span</value>
      <webElementGuid>db5c6dd1-75d2-4170-8109-81122e51df7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'labelOrderAmount' and (text() = '38.29' or . = '38.29')]</value>
      <webElementGuid>b63ee274-c403-4952-a5f7-ff81dfaba12c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
