<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select</name>
   <tag></tag>
   <elementGuidId>cc0a29cc-5473-48a2-8297-41b06e4ddc57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-ArrNewProducts-f1-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-ArrNewProducts-f1-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dd46874d-193f-44c1-b4d0-b097a00821ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>54c26d37-390c-4332-ba5e-8eb1bd46478a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ArrNewProducts-f1-container</value>
      <webElementGuid>7862757f-fa73-49f8-a845-df1edb3fcc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>4a235a38-2c1d-4478-99b8-b6eac8c8388c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>51a967bc-65d6-453d-847a-b2132a009fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>a8df2838-bf9f-4c6c-a931-f45c015faa7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>dc817c3f-e45c-4bf2-80c8-2bb9d847b45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ArrNewProducts-f1-container&quot;)</value>
      <webElementGuid>5f6408e6-8126-4cc3-a020-4c047895ed43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-ArrNewProducts-f1-container']</value>
      <webElementGuid>791cd187-d5f7-4406-a88b-71766024402a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='product']/tr/td/span/span/span/span</value>
      <webElementGuid>0a3f404b-9070-4bf7-a5da-ec68fa6d701f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[2]/following::span[4]</value>
      <webElementGuid>c1723cce-c249-4e03-b2d6-92e145defea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[1]/following::span[4]</value>
      <webElementGuid>7261a5fc-0a69-4e4d-9f0d-20efe683aa4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Charge :'])[1]/preceding::span[3]</value>
      <webElementGuid>c8e1b416-6c38-44f5-95c3-59b4079a488c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tip Amount :'])[1]/preceding::span[3]</value>
      <webElementGuid>8989cd14-db2d-4661-b39c-996a4079a6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/span/span/span</value>
      <webElementGuid>65c49b6f-089c-4314-848a-3c2ae2468764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-ArrNewProducts-f1-container' and @title = 'Select' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>0d3f4c85-ef5a-46b9-b2a2-240aeb754d1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
