<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login as a Admin User_login_view</name>
   <tag></tag>
   <elementGuidId>8f0ec953-0921-458c-a832-d3c41c9663d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_view</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_view']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04a24153-fd38-4b9e-a4fa-3049ee10245e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79324783-ca1f-4a6f-bf0a-949e2a78b8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>32103ecd-a0b7-474f-8569-d5c4eee1d0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login_view</value>
      <webElementGuid>4641b3c1-4857-43dc-8aff-984ff2fab3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_view</value>
      <webElementGuid>29704c24-fad4-4228-92ae-9d08f16d5743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>7debe008-7924-471b-b587-934577b887f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_view&quot;)</value>
      <webElementGuid>c22991a5-4bc0-4066-8bdc-3e420f98e30e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_view']</value>
      <webElementGuid>ba2dde83-f4c5-4daa-aa73-71bb044b98e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a3579d12-fa22-4091-a1bf-8e409c8bb346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'login_view' and @id = 'login_view' and @placeholder = 'Username']</value>
      <webElementGuid>fb21959a-adca-471b-96df-1ebe380c46b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
