<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>ba3e9d22-e5f0-4c08-9430-b79a70844cfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form > button.header_button > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-autocomplete']/form/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9717007e-6505-47d0-a6b4-ff93e77927fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/front/assets/images/search-icon.png</value>
      <webElementGuid>bcfd2607-0813-4ca6-9cca-eeaa7d19701e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-autocomplete&quot;)/form[1]/button[@class=&quot;header_button&quot;]/img[1]</value>
      <webElementGuid>96f37f1b-e95e-41c1-ae95-d6d19c0ff2e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-autocomplete']/form/button/img</value>
      <webElementGuid>f7fa58e2-1e19-48ab-bda4-3d9367ef436e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev.thcitsolutions.com/vrajfresh/front/assets/images/search-icon.png')]</value>
      <webElementGuid>4ec76b62-4b68-47c9-886d-eee6da94a8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/img</value>
      <webElementGuid>52d606c2-0888-46a5-9583-12dccc188794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.thcitsolutions.com/vrajfresh/front/assets/images/search-icon.png']</value>
      <webElementGuid>89e48267-24d5-4991-88c3-49af24b5bc2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
