<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1 (1)</name>
   <tag></tag>
   <elementGuidId>962f67af-2390-40f7-b99a-1e724a74e673</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form > button.header_button > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-autocomplete']/form/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>893bf693-e500-4c94-b468-d6ff6826e69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/front/assets/images/search-icon.png</value>
      <webElementGuid>a8b3df50-2226-46a3-84ca-ab3827ebd9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-autocomplete&quot;)/form[1]/button[@class=&quot;header_button&quot;]/img[1]</value>
      <webElementGuid>d5fb40f2-e51b-4263-9fa5-1d0c535c2701</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-autocomplete']/form/button/img</value>
      <webElementGuid>7135a1ca-6976-4b44-a4e5-7f74c97b20b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev.thcitsolutions.com/vrajfresh/front/assets/images/search-icon.png')]</value>
      <webElementGuid>4487c774-9c03-4d27-9052-cbf4ee65f46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/img</value>
      <webElementGuid>f290914a-c6e3-4e9a-bccc-0cc65ea8f51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.thcitsolutions.com/vrajfresh/front/assets/images/search-icon.png']</value>
      <webElementGuid>260afc9d-d0c9-45b4-b635-52a330722d59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
