<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Order Status_2223</name>
   <tag></tag>
   <elementGuidId>fbfe7055-00ba-40c3-9ff9-fefc68ce54af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblListData']/tbody/tr/td/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#2223</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>af8ea056-ec82-4440-97e7-0e9d08885029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>https://www.vrajfresh.com/admin/adminpanel/controller_order/update_order/</value>
      <webElementGuid>b25956a1-8805-4b2b-9877-4b7671ce2dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2223</value>
      <webElementGuid>fca8304b-9db1-4dbc-ba21-ddff0d3b55e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Order Edit</value>
      <webElementGuid>87cba739-30a7-4b64-9559-2ef7e28cf303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit_popup btn btn-default btn-sm</value>
      <webElementGuid>5eca42bd-d2a7-4ca5-a0d9-06b9516f95a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblListData&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[1]/div[@class=&quot;btn-group&quot;]/a[@id=&quot;2223&quot;]</value>
      <webElementGuid>85733729-b5d0-4402-a943-1d4a4cda174e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='2223']</value>
      <webElementGuid>b97d279f-291c-4d48-8b2e-9a1afd94ef6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblListData']/tbody/tr/td/div/a</value>
      <webElementGuid>503f72b2-3bd9-4c71-b320-9f355783a971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Status'])[2]/following::a[1]</value>
      <webElementGuid>9e2b8cba-576e-4bbd-892a-80be81d7d744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[2]/following::a[1]</value>
      <webElementGuid>29e3f707-da16-46d9-bf4d-336e3949fb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing'])[2]/preceding::a[4]</value>
      <webElementGuid>5a33010e-7d97-4011-9e04-bebc9d721e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/a</value>
      <webElementGuid>20fed95e-d2fc-42d8-b5ab-1f4185ff4f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '2223' and @title = 'Order Edit']</value>
      <webElementGuid>af7e0fcc-cd02-4267-b411-628a9459201c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
