<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PAGE IS LOADING_txtSearchKeyWord</name>
   <tag></tag>
   <elementGuidId>00f5a6af-9f0f-4ccc-8002-47b135676481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSearchKeyWord']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtSearchKeyWord</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2ae0c70-4b1c-4572-a7d6-493ed04b17f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>10aff39b-43ad-430a-9a69-6a1e51d20675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ffa4983-96c3-424e-ab84-e9aa09d75c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>extra_field form-control</value>
      <webElementGuid>b24a18c5-dce4-4ce3-a862-7b06073c24cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtSearchKeyWord</value>
      <webElementGuid>4c337158-dd95-4d08-b0a8-c49952529a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSearchKeyWord</value>
      <webElementGuid>794119c6-e4b1-425e-b3ee-6f81d383f8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Keyword</value>
      <webElementGuid>30a8f8db-57ea-4260-8b36-087996c34ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSearchKeyWord&quot;)</value>
      <webElementGuid>79320f31-677a-4336-8c1e-50be10b402e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSearchKeyWord']</value>
      <webElementGuid>811c5674-74a5-4dc8-bf64-9e6f66ec044b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmListDataFilter']/div/input</value>
      <webElementGuid>40ee58aa-8034-453c-8d8c-cb778af7e581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1d28c646-c654-46f5-a9dd-f1fc6d57969b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txtSearchKeyWord' and @id = 'txtSearchKeyWord' and @placeholder = 'Search Keyword']</value>
      <webElementGuid>0c05ef23-74fc-4330-8adc-9f01058c4b08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
