<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_33.29</name>
   <tag></tag>
   <elementGuidId>f9a177f8-f97c-4f8a-9220-cca4159fc0a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='labelOrderAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#labelOrderAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2893e2f8-ea03-44e3-8275-3bc6d66c6779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>labelOrderAmount</value>
      <webElementGuid>f153d737-b2b4-442c-af38-4d463f23b412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>33.29</value>
      <webElementGuid>cda5910e-89e9-4bf8-8a59-441575901d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;labelOrderAmount&quot;)</value>
      <webElementGuid>37c4a102-13fe-43ff-918d-a4fe9fb266ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='labelOrderAmount']</value>
      <webElementGuid>6bb82742-006c-4260-aced-fe063ddfdc1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='banner_frm']/div/div[3]/label[2]/span</value>
      <webElementGuid>da39b258-6da6-4d50-8934-534c1669cb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Amount :'])[1]/following::span[1]</value>
      <webElementGuid>3049b415-e440-4b13-bea6-ccdc8c5f1ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No, please refund for unavailable items'])[1]/preceding::span[1]</value>
      <webElementGuid>98502722-d258-4fd0-9a64-718ce8f187b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Amount :'])[1]/preceding::span[1]</value>
      <webElementGuid>3063e85c-d585-4c7e-bc4f-bdb077996bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span</value>
      <webElementGuid>7c0d1138-c83b-4359-ac05-be78daed745c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'labelOrderAmount' and (text() = '33.29' or . = '33.29')]</value>
      <webElementGuid>8fcd36d9-cfac-46ad-be33-9dee598f93c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
