<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Instant Mix (1)</name>
   <tag></tag>
   <elementGuidId>8c82a5dd-037b-421d-878c-520dc014558b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(18) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main-menu']/li/div/ul/li[18]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7d55dec1-8e83-457b-9586-9a9c52322eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/front/category/instant-mix</value>
      <webElementGuid>f9239811-a2a2-4592-99c2-9a5c16eccf06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instant Mix</value>
      <webElementGuid>47e352f8-907d-46a1-b2a7-9008e067c6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-menu&quot;)/li[1]/div[@class=&quot;submenu&quot;]/ul[1]/li[18]/a[1]</value>
      <webElementGuid>3fe37a37-ea63-4a45-8c77-759e8151fd4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main-menu']/li/div/ul/li[18]/a</value>
      <webElementGuid>d26dafe5-1b58-48bf-bb07-3413842c4954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Instant Mix')]</value>
      <webElementGuid>d30dadf5-c64d-46db-9f86-7c9994cc13f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Snacks'])[1]/following::a[1]</value>
      <webElementGuid>077b4f7b-f24d-4c24-a5ae-3884b0eaa2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oil &amp; Ghee'])[1]/following::a[2]</value>
      <webElementGuid>77a7d758-163a-4921-88d0-1f0c7a70a598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dal &amp; Beans'])[1]/preceding::a[1]</value>
      <webElementGuid>8617625c-cbf6-4974-9ce6-a5622a33ba6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fresh Produce'])[1]/preceding::a[2]</value>
      <webElementGuid>9d72b65a-ef35-4f22-ab69-963fc750f8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Instant Mix']/parent::*</value>
      <webElementGuid>cb6947c1-91c7-43dd-a4c6-efa9c251c3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dev.thcitsolutions.com/vrajfresh/front/category/instant-mix')]</value>
      <webElementGuid>ca928d8a-3388-45ae-84fd-6546653e4fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[18]/a</value>
      <webElementGuid>db39ae89-68de-4868-a7e8-99b65213e120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev.thcitsolutions.com/vrajfresh/front/category/instant-mix' and (text() = 'Instant Mix' or . = 'Instant Mix')]</value>
      <webElementGuid>902584cb-0a97-4cc3-a16e-3cf69419bdf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
