<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>9717ddd4-63c7-47cd-af77-14c9f068f144</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_1512</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_1512']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a51fbc08-2d31-4728-929f-ab9c62000498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_1512</value>
      <webElementGuid>cf42e61e-a31f-4b0b-9737-540b022f847e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add_cart </value>
      <webElementGuid>dfc0a76b-352d-4c7e-ad35-8ae0a0636369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isperisible</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8211932c-7057-411c-86e6-dd29e2634d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productslug</name>
      <type>Main</type>
      <value>gits-gulab-jamun</value>
      <webElementGuid>397dd765-cbbb-4c69-9ab8-d93063fc3a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productimage</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/admin/uploads/products/7092C9DC-8102-4305-82C2-18369CC7E0CB.jpg</value>
      <webElementGuid>164615d2-9bf6-485a-81c4-b4c08763a30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productname</name>
      <type>Main</type>
      <value>Gits Gulab Jamun</value>
      <webElementGuid>310ae584-baeb-44b1-8e08-72154c9f0b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>1.99</value>
      <webElementGuid>d432e7ed-1d2d-42bc-a092-6a7bd2a44efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productid</name>
      <type>Main</type>
      <value>1512</value>
      <webElementGuid>3e035fa9-5b89-4ba5-b8e5-f382c17c35a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productweight</name>
      <type>Main</type>
      <value>0.22</value>
      <webElementGuid>264ee77f-472d-4ab9-b23a-81184c3b574b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-producttax</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>14c9a5a5-2929-4295-8e5e-fc256eaf614b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>95778846-2ccc-44a9-8e17-acbd53125d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_1512&quot;)</value>
      <webElementGuid>fa768fb7-66ec-4047-9ffb-b4a0d8ebda89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_1512']</value>
      <webElementGuid>127a685d-29db-47a3-8e97-222ebc840045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_product']/div/div/ul/li[2]/button</value>
      <webElementGuid>b7b94a83-0c54-479f-be6b-d28aa0122915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::button[1]</value>
      <webElementGuid>2aef015c-dbfa-4f6b-b0bf-349eb0826191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::button[2]</value>
      <webElementGuid>a440d7c1-4733-4936-b8ca-98e198c054ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@vrajfresh.com'])[1]/preceding::button[1]</value>
      <webElementGuid>4bb15012-5411-4486-9ebc-8ab5af1ee2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>dbeb4b3b-7a96-4f1d-b9d5-4505815dbc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[2]/button</value>
      <webElementGuid>ded3001d-3c0c-4aff-8008-3f21ee86f9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_1512' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>28d11224-09a8-4e32-81cb-0bca45c5de0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
