<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Gits Gulab Jamun (1)</name>
   <tag></tag>
   <elementGuidId>4d191378-9df2-477f-928f-8e3c3bf0f03b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='category_product']/div[13]/div/a/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>f17538ea-90af-4e90-9796-07c3963d5582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gits Gulab Jamun...</value>
      <webElementGuid>fd278df0-ad3c-4859-9db4-506a12d2701f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_product&quot;)/div[@class=&quot;product-box&quot;]/div[1]/a[1]/h4[1]</value>
      <webElementGuid>d744b572-7037-40b9-9e24-ad2878d1a71e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_product']/div[13]/div/a/h4</value>
      <webElementGuid>d5ad277e-26f7-4dd9-9e33-f7e0085ca88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[12]/following::h4[1]</value>
      <webElementGuid>d07da39b-a0b5-4732-b2a1-30690a7ee8f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[12]/following::h4[1]</value>
      <webElementGuid>57179ed9-0513-4dfd-9a56-2d29c0b9ec3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[13]/preceding::h4[1]</value>
      <webElementGuid>255ef0b0-6322-4623-acd2-96d3a5112871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[13]/preceding::h4[1]</value>
      <webElementGuid>bacc921b-e07a-4f15-bbbe-a0e2111417b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gits Gulab Jamun...']/parent::*</value>
      <webElementGuid>5bd29a27-5299-4dca-ae5e-997538346d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/a/h4</value>
      <webElementGuid>f66c56b8-8c7c-436f-ae52-bde55bee332d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Gits Gulab Jamun...' or . = 'Gits Gulab Jamun...')]</value>
      <webElementGuid>52274744-dd63-4f34-baca-fd09c33d5b3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
