<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>64ba76c7-5dfe-4019-805a-82e5048bdd34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form > button.header_button > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-autocomplete']/form/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bc0ade4c-7c94-4b53-b606-70b0e224b602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/front/assets/images/search-icon.png</value>
      <webElementGuid>55818939-a637-46b2-83a1-fc87a45c77ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-autocomplete&quot;)/form[1]/button[@class=&quot;header_button&quot;]/img[1]</value>
      <webElementGuid>cac90b89-acd5-4b76-ad12-3d8578f2b56a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-autocomplete']/form/button/img</value>
      <webElementGuid>21639487-cca4-48d9-8e98-345c50e49038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev.thcitsolutions.com/vrajfresh/front/assets/images/search-icon.png')]</value>
      <webElementGuid>e59e32af-47fc-4dc6-a4f0-a26d72ecc50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/img</value>
      <webElementGuid>b67af242-a224-46be-acb8-e9ecde0942f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.thcitsolutions.com/vrajfresh/front/assets/images/search-icon.png']</value>
      <webElementGuid>2b89b9cf-424a-44c3-8caa-0773c2fddc3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
