<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>4350e1b6-5123-489b-b55d-f7c050156719</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='category_product']/div[16]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>076a401e-d3f1-4026-a82f-429dae0be09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/admin/uploads/products/18169258-724E-44B2-A029-EC07C923400D.jpg</value>
      <webElementGuid>cf43beb9-8120-43fe-a508-4639e5424a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.src=&quot;https://dev.thcitsolutions.com/vrajfresh/admin/uploads/logo-2.png&quot;</value>
      <webElementGuid>09d7aafc-7541-4753-8ff8-8aedda547c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_product&quot;)/div[@class=&quot;product-box&quot;]/a[1]/img[1]</value>
      <webElementGuid>bf15ab3e-d109-419f-a651-1ebc45405cba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_product']/div[16]/a/img</value>
      <webElementGuid>4a2e8cab-4814-4694-b7bf-b8c58231110e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev.thcitsolutions.com/vrajfresh/admin/uploads/products/18169258-724E-44B2-A029-EC07C923400D.jpg')]</value>
      <webElementGuid>a32440c7-6783-4962-a05e-cdbc904f8646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/a/img</value>
      <webElementGuid>8edd8788-382a-48fc-899f-83616b022be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.thcitsolutions.com/vrajfresh/admin/uploads/products/18169258-724E-44B2-A029-EC07C923400D.jpg']</value>
      <webElementGuid>9159f419-c8fa-43d0-ba21-36e0b770ee73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
