<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Instant Mix_1</name>
   <tag></tag>
   <elementGuidId>0213aab1-c3e0-45b3-b340-fb8318b5c925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(11) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main-menu']/li/div/ul/li[11]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>541ca6c7-8a36-48a4-a802-882c7daee316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.vrajfresh.com/category/instant-mix</value>
      <webElementGuid>50a29d88-d812-4f3d-b9f8-77d5af330a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instant Mix</value>
      <webElementGuid>608fde0f-654c-4050-bfbc-b30beeabead2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-menu&quot;)/li[1]/div[@class=&quot;submenu&quot;]/ul[1]/li[11]/a[1]</value>
      <webElementGuid>fed052d0-2d1f-4b8e-bfed-333ebeb2aab3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main-menu']/li/div/ul/li[11]/a</value>
      <webElementGuid>e87fffb6-59ce-4923-bf1d-03b324c8d744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Instant Mix')]</value>
      <webElementGuid>98286a58-c096-4917-926b-af4171961551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salt Sugar &amp; Jaggery'])[1]/following::a[1]</value>
      <webElementGuid>2fabb7cf-d5bc-45f4-881a-07c7ca74fa32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rice'])[1]/following::a[2]</value>
      <webElementGuid>783ae355-017a-4ba7-9d5f-a888e1787674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Flour'])[1]/preceding::a[1]</value>
      <webElementGuid>24dedd8f-5f51-464b-a53c-b9acb24f786c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canned Food'])[1]/preceding::a[2]</value>
      <webElementGuid>fe65cffe-fc8b-467e-9bf1-80c84b734c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Instant Mix']/parent::*</value>
      <webElementGuid>128dc258-b2f4-4ec0-8e07-e46929d370f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.vrajfresh.com/category/instant-mix')]</value>
      <webElementGuid>01c2a607-ae47-475d-b769-3599c1cf4c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a</value>
      <webElementGuid>5eedddac-cf62-4488-85ef-f5fd6f3b8127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.vrajfresh.com/category/instant-mix' and (text() = 'Instant Mix' or . = 'Instant Mix')]</value>
      <webElementGuid>01efeb0b-22e6-44fb-b24e-9d0d32261d2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
