<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Remove Tip</name>
   <tag></tag>
   <elementGuidId>b443edab-72b7-429c-9ae4-e16e710e41a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tip_remove_button > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='removeTipAmount()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b789f8ad-7b62-46cc-a35a-5ffe066649d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>13d8a4a2-423e-482f-af18-9f7154dd3d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>removeTipAmount()</value>
      <webElementGuid>7b6aec44-5321-44cd-bdc4-a3fdaccc68c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove Tip</value>
      <webElementGuid>6483c461-cf72-47ff-8623-e802f0367d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tip_remove_button&quot;)/a[1]</value>
      <webElementGuid>d944fa0b-1673-4005-934d-28b20ecb5125</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='removeTipAmount()']</value>
      <webElementGuid>bbc6268d-5784-4a5f-9f25-0bb9ff971587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='tip_remove_button']/a</value>
      <webElementGuid>f2a87a94-bb9d-4a5f-8599-24f94b20f4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Remove Tip')]</value>
      <webElementGuid>0481bac4-01a9-4a64-bfab-d6b9f2adc2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Tip'])[1]/following::a[1]</value>
      <webElementGuid>15c31112-c14a-4bea-acb4-4415e5c6f1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter valid amount'])[1]/following::a[2]</value>
      <webElementGuid>5763ca51-4677-44a1-b3f2-52e26cc15b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Notes (optional)'])[1]/preceding::a[1]</value>
      <webElementGuid>79c687f4-fe40-45be-8822-cb65c74a460a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remove Tip']/parent::*</value>
      <webElementGuid>96e8683f-17da-49ec-9925-5ef15172ed8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>82eea0a8-b95c-48fa-be13-0b1a71d1b6ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>7f262e2a-f6c6-4d30-809d-614ed2cd202b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Remove Tip' or . = 'Remove Tip')]</value>
      <webElementGuid>299c724a-ab0b-4366-b312-13319b3987aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
