<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_10</name>
   <tag></tag>
   <elementGuidId>cbf6d005-2ed2-4ca3-b579-5de3a657e740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order_tip_10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='order_tip_10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bb7d1ef6-9b28-4266-a4ed-d5ba56884be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_tip_10</value>
      <webElementGuid>190fe9a2-a157-421e-86c5-477c42fcbfcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>11f6600d-b69d-4bd3-b438-72057c0c3ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order_tip</value>
      <webElementGuid>2bb1487f-ca1b-468d-a331-fb09da2d5872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tip</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>9c4ca1e2-1504-45e4-ac61-84fa00473da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 10</value>
      <webElementGuid>3c4c3814-eec2-4104-8ec3-f1514e7df40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_tip_10&quot;)</value>
      <webElementGuid>038e9eb5-a533-4eab-a2dc-4f2a06f3306e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='order_tip_10']</value>
      <webElementGuid>841552c4-7275-4f2d-99e4-721661b14d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/section/div/div/div[11]/button[2]</value>
      <webElementGuid>f1ecf061-41f1-4816-a400-be2a226adf96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$5'])[1]/following::button[1]</value>
      <webElementGuid>1bad19a8-844d-4ff0-b82d-26de0e49e60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tip'])[1]/following::button[2]</value>
      <webElementGuid>35b54753-2856-49fa-9876-b842e73ae87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 15'])[1]/preceding::button[1]</value>
      <webElementGuid>322868f7-8d8f-4a30-ad05-506bfa47b074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 20'])[1]/preceding::button[2]</value>
      <webElementGuid>dd9f9585-46be-4494-97f5-0df9a9eff4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$ 10']/parent::*</value>
      <webElementGuid>b9fef7c2-60d3-4451-b1b5-2ff93251105d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>748f3e24-66bb-4ff3-b23a-9201c42e04e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'order_tip_10' and @type = 'button' and (text() = '$ 10' or . = '$ 10')]</value>
      <webElementGuid>32eb3d3d-cb6f-403c-9727-2af285da2f50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
