<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Ramdev aata</name>
   <tag></tag>
   <elementGuidId>dc7677d2-d064-474d-8991-6e873858d9d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='category_product']/div/div/a/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>7f02b665-98b2-4647-8fe7-da1c3133ed04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ramdev aata</value>
      <webElementGuid>38913b74-30cf-4a9b-ad8d-e117e0164085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_product&quot;)/div[@class=&quot;product-box&quot;]/div[1]/a[1]/h4[1]</value>
      <webElementGuid>be85ead7-6d90-47be-adde-d2b79481df90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_product']/div/div/a/h4</value>
      <webElementGuid>44ed0cfd-7cfa-47e2-b436-d45ce6a76875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::h4[1]</value>
      <webElementGuid>50f0f3d3-a654-4e2f-88f0-8933c047be60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAGS'])[1]/following::h4[1]</value>
      <webElementGuid>d94e61b3-b9f9-4616-a02c-19a33c424368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Out of stock'])[1]/preceding::h4[1]</value>
      <webElementGuid>185b0992-a520-407d-9ba6-946243a0e13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::h4[1]</value>
      <webElementGuid>5a8dd55e-360a-48ce-81e2-8a3505bfec58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ramdev aata']/parent::*</value>
      <webElementGuid>0a146817-83ad-4aae-8cd9-6489d356e310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>8cbd8f7d-037d-40e5-b790-e927825ac507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Ramdev aata' or . = 'Ramdev aata')]</value>
      <webElementGuid>2205a70d-bef9-4a04-a366-72a0d5456829</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
