<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>2281ee41-5aca-40ce-9c25-c549bd7b545b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='popular-items']/div/div/div[4]/a/img)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5e72a90c-2907-458a-8558-b37faeb3ca6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/admin/uploads/products/B58366DF-EB88-495D-89CC-4DA1475F00EF.jpg</value>
      <webElementGuid>aaaa6616-045c-455c-8c3a-4c84831e785e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.src=&quot;https://dev.thcitsolutions.com/vrajfresh/front/assets/images/logo-2.png&quot;</value>
      <webElementGuid>4265cafe-d21b-46a4-bfd5-dcf1a22b59bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popular-product1&quot;)/div[@id=&quot;popular-items&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;product-box slick-slide slick-active&quot;]/a[1]/img[1]</value>
      <webElementGuid>7eba6931-68b3-457f-8ee9-1f27a7b770eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='popular-items']/div/div/div[4]/a/img)[2]</value>
      <webElementGuid>5085a4ff-bd5b-487f-81ac-215831bd8574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev.thcitsolutions.com/vrajfresh/admin/uploads/products/B58366DF-EB88-495D-89CC-4DA1475F00EF.jpg')]</value>
      <webElementGuid>2e557682-a239-4519-835c-ae689529c8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div/div/div/div/div/div[4]/a/img</value>
      <webElementGuid>9c4be524-b3ab-4c67-b0e6-a1d6c82f35ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.thcitsolutions.com/vrajfresh/admin/uploads/products/B58366DF-EB88-495D-89CC-4DA1475F00EF.jpg']</value>
      <webElementGuid>dc3b2bc6-0001-4aad-9938-a0020d354d7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
