<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4_5_6_7_8</name>
   <tag></tag>
   <elementGuidId>ad530ac6-5573-4b57-a05a-abb58e22ccfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.header_button_cart > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[contains(@src,'https://dev.thcitsolutions.com/vrajfresh/front/assets/images/go.png')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d2a4e35a-eec2-4c19-886f-37759f659b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/front/assets/images/go.png</value>
      <webElementGuid>201cd27f-25a3-4466-baf4-b9479526d518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;billing-page cart-min&quot;]/div[@class=&quot;container container-flex&quot;]/div[@class=&quot;cart_totals&quot;]/div[@class=&quot;zip-code_cart&quot;]/button[@class=&quot;header_button_cart&quot;]/img[1]</value>
      <webElementGuid>08595b00-2b34-45f6-b341-7d539e39594d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://dev.thcitsolutions.com/vrajfresh/front/assets/images/go.png')])[2]</value>
      <webElementGuid>68a360a2-cd3d-4c9e-bb43-83574ef2d699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/img</value>
      <webElementGuid>3508d0e1-efc9-492d-8594-6fdbbcf43508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.thcitsolutions.com/vrajfresh/front/assets/images/go.png']</value>
      <webElementGuid>390c3934-6022-47bb-a076-90051a56f4aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
