<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>13119a1b-d41f-4b89-b118-2d7e33418480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='category_product']/div[4]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ad5c9cba-ae3d-442e-b861-e784b6f86f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.vrajfresh.com/admin/uploads/products/18169258-724E-44B2-A029-EC07C923400D.jpg</value>
      <webElementGuid>17999438-6aac-4141-bfc7-a675c5f33bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.src=&quot;https://www.vrajfresh.com/admin/uploads/logo-2.png&quot;</value>
      <webElementGuid>df602ce5-7c57-42a1-9a7d-903ab0c77d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_product&quot;)/div[@class=&quot;product-box&quot;]/a[1]/img[1]</value>
      <webElementGuid>478230be-d31d-4f23-ba21-25a2f7d80150</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_product']/div[4]/a/img</value>
      <webElementGuid>9f7af57a-b5cf-40db-9e9e-9ce4fe0dcbe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.vrajfresh.com/admin/uploads/products/18169258-724E-44B2-A029-EC07C923400D.jpg')]</value>
      <webElementGuid>c812332a-3f6b-4827-8342-11db27fe85f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/img</value>
      <webElementGuid>96fa041e-f7df-46ef-9676-8e0100aa4746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.vrajfresh.com/admin/uploads/products/18169258-724E-44B2-A029-EC07C923400D.jpg']</value>
      <webElementGuid>5039689d-472e-46b2-8118-4eb87f8ae7b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
