<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_2.00lb - 4.003.00lb - 5.00</name>
   <tag></tag>
   <elementGuidId>fac5f4ac-2471-4f53-88f9-fca234de41fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jumpMenu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jumpMenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e1510d47-782f-4b78-b2b9-5ff5077c651c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumpMenu</value>
      <webElementGuid>9aed3331-0f38-4c4c-a90d-1f9c5f06a262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jumpMenu</value>
      <webElementGuid>10c39fa8-51ff-41b1-9c0c-2e2a0c549608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>variants </value>
      <webElementGuid>e9fe1fbc-ae32-4668-92c4-310f3ea5c21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2.00lb - $4.003.00lb - $5.00</value>
      <webElementGuid>4864f871-2778-41df-9b1f-6ac4b675f8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_product&quot;)/div[@class=&quot;product-box&quot;]/div[1]/form[@id=&quot;form&quot;]/select[@id=&quot;jumpMenu&quot;]</value>
      <webElementGuid>fca7298f-d767-4e69-a6a5-206aba8d5ff2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jumpMenu']</value>
      <webElementGuid>2546b1ed-c28e-466e-b40e-422edf3c1608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/select</value>
      <webElementGuid>af78a2af-a993-43f9-9e39-7513d4048194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='vadilal Pista Ice cream'])[1]/following::select[1]</value>
      <webElementGuid>85dd9c3f-8536-42a9-bb3d-64605e9cb5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::select[1]</value>
      <webElementGuid>a8aa675c-bdde-4e8b-8f49-0de59fcd2840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::select[1]</value>
      <webElementGuid>3c1d1312-07e8-41d8-8b71-bac23a1754b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::select[1]</value>
      <webElementGuid>b651ce93-4354-420d-994d-6bffa4b14509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a18229dc-e6bf-4a95-95ac-d8d27565138f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jumpMenu' and @id = 'jumpMenu' and (text() = '2.00lb - $4.003.00lb - $5.00' or . = '2.00lb - $4.003.00lb - $5.00')]</value>
      <webElementGuid>49ef7b85-8165-4765-8ed1-000f35e50485</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
