<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login as a Admin User_login_view</name>
   <tag></tag>
   <elementGuidId>670fad7c-31ee-41a1-991c-d33842f4f9f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_view</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_view']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2b67011-45e7-4204-a3b5-e029b235afc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>615ea45f-8866-4495-8121-2ea2e50a2ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>abb2b853-cb92-4aa7-9085-f36c4e80bddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login_view</value>
      <webElementGuid>732bd08d-5463-4681-a95d-84341d9a2d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_view</value>
      <webElementGuid>d2b1f3c6-1043-45c3-a07e-6bc50a08c7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>754d8854-48b0-4710-b167-ac0b101cd3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_view&quot;)</value>
      <webElementGuid>88c04193-6fbe-475a-85f9-b53fe11550cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_view']</value>
      <webElementGuid>a4ae21ca-f92d-432e-99e7-737359944778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f1d84cdf-333c-42b2-8630-5d6a2cc4400d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'login_view' and @id = 'login_view' and @placeholder = 'Username']</value>
      <webElementGuid>87311d5a-82c8-4e91-a4cb-010c84f2bffe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
