<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add_1_2</name>
   <tag></tag>
   <elementGuidId>e42af6d2-4144-4c48-9ef0-cda51ac167ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_6456']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_6456</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1b52df64-866b-4c26-b5a4-71cc4af8b115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_6456</value>
      <webElementGuid>dfc4343e-95f4-42d0-9dd7-99c5d7f1859e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add_cart </value>
      <webElementGuid>3ed0d576-e51a-4d27-aa0c-ecc1a07ca974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isperisible</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>78d7f742-a417-44c2-a640-192b0df77e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productslug</name>
      <type>Main</type>
      <value>kinder-joy-20g-07oz</value>
      <webElementGuid>4efdc210-e7ac-4012-81bf-d008c28269e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productimage</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/admin/uploads/products/E3665E8F-B6B5-4DD5-B69C-DBBFEDA180D3.jpeg</value>
      <webElementGuid>e3253ee0-b230-4389-b311-6c4c34732082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productname</name>
      <type>Main</type>
      <value>Kinder Joy (20g  0.7Oz)</value>
      <webElementGuid>fa43393e-e0c5-4651-8747-1afe1144a21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>2.99</value>
      <webElementGuid>36324f3c-a28c-43c9-ad8c-5184fcd47a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productid</name>
      <type>Main</type>
      <value>6456</value>
      <webElementGuid>d914f923-e027-4148-8438-fcd2c7ced106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productweight</name>
      <type>Main</type>
      <value>0.04</value>
      <webElementGuid>6389ab44-04e1-4e24-a132-8d63e8e694d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-producttax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>13f307cb-2cc4-4bf7-aa5e-41caeaaa24bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>c426c922-7606-4e3d-8f38-e4ff3d9076d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_6456&quot;)</value>
      <webElementGuid>e0f1d3fd-f4cb-487a-8a47-54ee33c9a375</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_6456']</value>
      <webElementGuid>88330322-68e7-4f3b-b13f-a0fc39c899a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_product']/div[2]/div/ul/li[2]/button</value>
      <webElementGuid>323e5f84-56a4-4458-a454-0a3004432468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[2]/following::button[1]</value>
      <webElementGuid>38f26370-d9d8-404c-b13e-ef5aa5a3106a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::button[2]</value>
      <webElementGuid>e22be12f-11c9-4f31-98de-d0f6a669016f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@vrajfresh.com'])[1]/preceding::button[1]</value>
      <webElementGuid>8137e69a-4fa1-4f28-a872-922ece856b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]/button</value>
      <webElementGuid>4546fad0-7e93-41f9-ad4d-50efbdeb1f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_6456' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>4e2b837d-9123-4992-8c02-a9bdf7ca0261</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
