<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>8419de7e-d635-45e5-a67c-ffac4d5b15ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[contains(@src,'https://dev.thcitsolutions.com/vrajfresh/front/assets/images/go.png')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.header_button_cart > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>43609097-30a1-4dad-9359-116ca0e90710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/front/assets/images/go.png</value>
      <webElementGuid>a6e81a77-e594-47ee-850e-4ff0cd5e79d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;billing-page cart-min&quot;]/div[@class=&quot;container container-flex&quot;]/div[@class=&quot;cart_totals&quot;]/div[@class=&quot;zip-code_cart&quot;]/button[@class=&quot;header_button_cart&quot;]/img[1]</value>
      <webElementGuid>47f2df8b-d2ff-4c75-981a-d0b6156c25a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://dev.thcitsolutions.com/vrajfresh/front/assets/images/go.png')])[2]</value>
      <webElementGuid>6ed89c42-8741-4a1e-b1a0-bb390e10de20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/img</value>
      <webElementGuid>f2e75120-05f2-458e-95ec-9ed0590ba2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.thcitsolutions.com/vrajfresh/front/assets/images/go.png']</value>
      <webElementGuid>1bcc4be1-44f2-467c-b62a-abf329a5cd22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
