<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Grocery_but</name>
   <tag></tag>
   <elementGuidId>aa58b519-0b36-4b3e-a1fc-df258f7f5e4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.but</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main-menu']/li/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cdac7dd9-dfa0-4765-a62d-645ff025434b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>but</value>
      <webElementGuid>c75b1b45-e236-48f9-9b3c-1baded4651cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-menu&quot;)/li[1]/button[@class=&quot;but&quot;]</value>
      <webElementGuid>f708854a-2fb7-494d-8e7c-3681d13a0809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main-menu']/li/button</value>
      <webElementGuid>d0ef66c9-8229-4dfa-9870-0d6b05b090de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button</value>
      <webElementGuid>99b9299f-95a3-4edf-989f-b378757fc26d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
