<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_More Options (1)</name>
   <tag></tag>
   <elementGuidId>8d542810-0f82-4b68-aaed-4bdb511c147e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popular-items']/div/div/div[21]/a[2]/ul/li/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aacc42ed-c5d3-4f9c-b5b5-906822da043a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add_cart</value>
      <webElementGuid>9c2e0aa0-e05e-498c-b6de-7cd2603b972c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>More Options</value>
      <webElementGuid>339b9e3a-4c41-4a56-9cda-cda82c14b1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popular-product1&quot;)/div[@id=&quot;popular-items&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;product-box slick-slide slick-active&quot;]/a[2]/ul[1]/li[1]/button[@class=&quot;add_cart&quot;]</value>
      <webElementGuid>9c02c5d3-96e8-4025-982d-1ba4f5260cb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popular-items']/div/div/div[21]/a[2]/ul/li/button</value>
      <webElementGuid>91c1e242-19f3-4ac5-998a-a7f6e02b7a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kawan Flakey Paratha'])[2]/following::button[1]</value>
      <webElementGuid>dcf1f64c-bece-4213-a842-8c032f0c5f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[45]/following::button[1]</value>
      <webElementGuid>9af8d7c5-214b-46bf-9275-a38d44ba2141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Red rose juice'])[2]/preceding::button[1]</value>
      <webElementGuid>116c951f-4c7a-4878-afce-494c99ba78e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Options'])[12]/preceding::button[1]</value>
      <webElementGuid>c1141215-402c-4692-a209-370375dcaa29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/a[2]/ul/li/button</value>
      <webElementGuid>3ffc2027-4a29-4c2f-a44e-ffd91940440d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'More Options' or . = 'More Options')]</value>
      <webElementGuid>ad03458a-e09b-4eb2-b262-b7096aeceb39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
