<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Gits Gulab Jamun</name>
   <tag></tag>
   <elementGuidId>63c111ee-f951-4f33-b452-cadf8a7e5a01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='category_product']/div[13]/div/a/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>12e48094-833e-4646-83ea-06327ece3835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gits Gulab Jamun...</value>
      <webElementGuid>3c3221e8-5758-4cb8-8334-889e778a5628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_product&quot;)/div[@class=&quot;product-box&quot;]/div[1]/a[1]/h4[1]</value>
      <webElementGuid>a5faace0-3c4c-49d0-9f10-1ef9b8f41d24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_product']/div[13]/div/a/h4</value>
      <webElementGuid>ba9bef66-1c62-4caa-b03c-08f49ed8fa72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[12]/following::h4[1]</value>
      <webElementGuid>9bf47fec-1ad6-45e8-9c02-ae954787bdf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[12]/following::h4[1]</value>
      <webElementGuid>8254eac9-e2c1-4ef2-b9fa-5cd035b2e05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[13]/preceding::h4[1]</value>
      <webElementGuid>21cfdc7d-64ce-4390-9aaa-8f752326de2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[13]/preceding::h4[1]</value>
      <webElementGuid>166ca3a1-9fe3-43f2-840c-a17fa3021920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gits Gulab Jamun...']/parent::*</value>
      <webElementGuid>c5d22c70-a884-4203-88a4-c64cff7136fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/a/h4</value>
      <webElementGuid>1f274174-cedd-4839-a78d-67ca15f7bd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Gits Gulab Jamun...' or . = 'Gits Gulab Jamun...')]</value>
      <webElementGuid>0d1f54f8-07f9-47a6-9545-0126dcf2b48e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
