<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3 (1)</name>
   <tag></tag>
   <elementGuidId>e27b7d67-518e-4acf-9475-ac1764bb9e22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='category_product']/div[3]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.product-box > a > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0e4a7b63-5266-443b-adf8-62f0d6537453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.vrajfresh.com/admin/uploads/logo-2.png</value>
      <webElementGuid>e267287e-b1bc-4459-b9b2-a18819105068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.src=&quot;https://www.vrajfresh.com/admin/uploads/logo-2.png&quot;</value>
      <webElementGuid>ccda1c59-0652-46f4-9c5e-d7a09ee7fd81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_product&quot;)/div[@class=&quot;product-box&quot;]/a[1]/img[1]</value>
      <webElementGuid>54f004f0-5d00-4cea-ba5a-2b49b2d4b7db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_product']/div[3]/a/img</value>
      <webElementGuid>cac35933-f998-4c96-a9fb-3820166b4c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev.thcitsolutions.com/vrajfresh/admin/uploads/logo-2.png')]</value>
      <webElementGuid>52e52053-eb7e-4a59-982f-977d67b139a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/a/img</value>
      <webElementGuid>7e27291d-6a2d-44b5-893f-4f682b665c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.thcitsolutions.com/vrajfresh/admin/uploads/logo-2.png']</value>
      <webElementGuid>5d3af009-3eee-43a4-8f4b-2e2be28c35e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
