<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>d0521b8e-e974-44f1-90bb-ab6d5d787724</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[contains(@src,'https://www.vrajfresh.com/assets/images/go.png')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.header_button_cart > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6eaa687c-6a4c-49e3-b41d-80d1b6b5dedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.vrajfresh.com/assets/images/go.png</value>
      <webElementGuid>e35f2149-49ba-4a5b-ad7e-0193c659c8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;billing-page cart-min&quot;]/div[@class=&quot;container container-flex&quot;]/div[@class=&quot;cart_totals&quot;]/div[@class=&quot;zip-code_cart&quot;]/button[@class=&quot;header_button_cart&quot;]/img[1]</value>
      <webElementGuid>4b5d5ea9-546a-409e-9bfc-fe8910dab71f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.vrajfresh.com/assets/images/go.png')])[2]</value>
      <webElementGuid>61c5b297-c933-49a6-979c-e37647730fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/img</value>
      <webElementGuid>26fd6c60-9f6d-41aa-a0b7-9b17929b13d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.vrajfresh.com/assets/images/go.png']</value>
      <webElementGuid>e7defb1e-a19f-4eba-aaf9-cf11dfd22195</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
