<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes, please substitute unavailable it_302eac (1)</name>
   <tag></tag>
   <elementGuidId>5c3d8f19-3c1c-48ba-a6e7-9fdc28ab1b3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refund_for_unavailable']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#refund_for_unavailable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f474945-c924-44ab-bb9c-a086a7193f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refund_for_unavailable</value>
      <webElementGuid>f86abd46-1721-4698-a754-904033649d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refund_for_unavailable</value>
      <webElementGuid>a76c1c28-5123-4f69-af43-47ccb5142f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f510dc59-51ae-4c05-95b6-181d84484daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0af63ce1-1568-4603-8ceb-0aa2fe425728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refund_for_unavailable&quot;)</value>
      <webElementGuid>6ec7bb80-be72-4b19-8cc2-25c040daa520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refund_for_unavailable']</value>
      <webElementGuid>4fda59be-f426-4e6a-8830-b823f9e9d68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/section/div/div/input[5]</value>
      <webElementGuid>4935a8c7-c8e0-4474-9a27-05ca119a9d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>9d9deb84-a6c3-456c-963f-3de23a88e51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'refund_for_unavailable' and @id = 'refund_for_unavailable' and @type = 'radio']</value>
      <webElementGuid>d432610a-0131-49be-ade9-370467717386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
