<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login as a Admin User_login_view</name>
   <tag></tag>
   <elementGuidId>fcfad039-d47e-4021-bc60-c8d22e3acd76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_view</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_view']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f522b312-0561-4b6b-b067-5496208471cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04ab73ae-f5fa-4fa6-96ce-b909d4064065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>917e7769-41da-45d8-b13c-4323d0ea8555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login_view</value>
      <webElementGuid>b4627221-5825-48e1-8e60-9873395a188c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_view</value>
      <webElementGuid>60e58882-df2b-400a-a129-929e055e36a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>a6743418-13fc-4142-ac16-289fb1d3aa85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_view&quot;)</value>
      <webElementGuid>77f56f77-bde8-480d-8917-96f57df4b575</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_view']</value>
      <webElementGuid>2eabdd3e-7ced-46e6-9d1a-d156b70253dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c688e766-c524-4091-b6d2-97c0e19db1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'login_view' and @id = 'login_view' and @placeholder = 'Username']</value>
      <webElementGuid>7ccce187-6820-4788-a396-7f81bfd74998</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
