<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Roti Paratha  Naan</name>
   <tag></tag>
   <elementGuidId>905f10f9-b53e-4a74-aae5-c2224567b67b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main-menu']/li[3]/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > div.submenu > ul > li:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c358149f-cc1b-426b-b0a3-a12ed664b3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/front/category/roti-paratha--naan</value>
      <webElementGuid>2aac76db-0964-4a57-b78c-27916a611d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Roti Paratha &amp; Naan</value>
      <webElementGuid>f0cb4078-6357-42b5-88d9-eedc5e1b6a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-menu&quot;)/li[3]/div[@class=&quot;submenu&quot;]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>c1e77e84-86a3-4e12-886b-69eb9287d47d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main-menu']/li[3]/div/ul/li[2]/a</value>
      <webElementGuid>b30695eb-3e14-4153-8d3d-c412e26e628b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Roti Paratha &amp; Naan')]</value>
      <webElementGuid>c807c8e8-4d60-4879-bfcd-54b6f8cf1122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ice Cream'])[1]/following::a[1]</value>
      <webElementGuid>26cf2ae5-e8e2-4af7-98b0-e489a086fb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frozen'])[2]/following::a[2]</value>
      <webElementGuid>ca7f1f7d-154c-4b20-82d5-6ebf0cb7113d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cut Vegetable'])[2]/preceding::a[1]</value>
      <webElementGuid>46b353a7-b331-430a-b7ea-bcf50a80dbad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appetizer'])[1]/preceding::a[2]</value>
      <webElementGuid>622460dd-2b4c-4fa3-962d-bf72462955e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Roti Paratha &amp; Naan']/parent::*</value>
      <webElementGuid>b8473337-aef2-49f4-bb52-84e6582031a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dev.thcitsolutions.com/vrajfresh/front/category/roti-paratha--naan')]</value>
      <webElementGuid>6dbc5374-c6ae-4faa-9773-78a3155bbd83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/ul/li[2]/a</value>
      <webElementGuid>81dfde01-663a-482f-b0ab-0e0d9f44c39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev.thcitsolutions.com/vrajfresh/front/category/roti-paratha--naan' and (text() = 'Roti Paratha &amp; Naan' or . = 'Roti Paratha &amp; Naan')]</value>
      <webElementGuid>8a8978b2-83ed-4f03-ba02-266379e0d4c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
