<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>66927dd0-b022-4811-9c35-69d4278fa6c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://dev.thcitsolutions.com/vrajfresh/front/assets/images/user-icon.png')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.vraj-login > a > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>65db5866-1980-4a23-8fd3-fa2844d88aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/front/assets/images/user-icon.png</value>
      <webElementGuid>9cba7f39-bb21-466e-90d7-02aa1f879de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[1]/div[@class=&quot;container container-flex header&quot;]/div[@class=&quot;my-account&quot;]/ul[1]/li[@class=&quot;vraj-login&quot;]/a[1]/img[1]</value>
      <webElementGuid>018339b6-bb89-488b-a261-8a4fc7adb884</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev.thcitsolutions.com/vrajfresh/front/assets/images/user-icon.png')]</value>
      <webElementGuid>8f3b8a34-09e4-4ba2-b7b4-bbb7acbe395e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>bf4aa248-adeb-4cde-9473-68ea6dee2bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.thcitsolutions.com/vrajfresh/front/assets/images/user-icon.png']</value>
      <webElementGuid>4b4afa95-8200-4d34-a8c8-45ba3b5aacd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
