<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>87f052e3-bd54-4bc1-8668-a96bd66bff96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='category_product']/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.product-box > a > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>49926465-e516-4896-89e8-4c3a68549051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/admin/uploads/products/18169258-724E-44B2-A029-EC07C923400D.jpg</value>
      <webElementGuid>d8db506d-4d40-41ea-816b-55785b6beb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.src=&quot;https://dev.thcitsolutions.com/vrajfresh/admin/uploads/logo-2.png&quot;</value>
      <webElementGuid>87814783-ed28-400c-a6b4-0b5ebb93d719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_product&quot;)/div[@class=&quot;product-box&quot;]/a[1]/img[1]</value>
      <webElementGuid>e351e510-e1fd-4574-a317-2f7dfb666bc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_product']/div/a/img</value>
      <webElementGuid>f7e697b0-3e06-43be-b1a7-cb5f45a602df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev.thcitsolutions.com/vrajfresh/admin/uploads/products/18169258-724E-44B2-A029-EC07C923400D.jpg')]</value>
      <webElementGuid>cdf0b80b-a6f1-4923-9c44-934d07e3e6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>d743ef66-a57b-4d8e-9485-992343d2b50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.thcitsolutions.com/vrajfresh/admin/uploads/products/18169258-724E-44B2-A029-EC07C923400D.jpg']</value>
      <webElementGuid>2a40d622-0d7e-4df9-b540-a6178da43171</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
