<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes, please substitute unavailable it_302eac</name>
   <tag></tag>
   <elementGuidId>dbbe09cd-c572-468c-9c78-64b8d3f1a90f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refund_for_unavailable']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#refund_for_unavailable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e27293b-a54c-4f67-b0cc-0c9bb64ed85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refund_for_unavailable</value>
      <webElementGuid>c198c1bf-5944-4b7b-ab9f-f522beb8cf03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refund_for_unavailable</value>
      <webElementGuid>009f3443-82ff-489a-acf8-3c8dca3988a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>340ab7ee-47bb-4308-9191-59a52b9d5261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ec0d3b6a-5700-4308-82ac-e94cc761a737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refund_for_unavailable&quot;)</value>
      <webElementGuid>d023ad44-2616-4bfe-9167-5188d7633b8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refund_for_unavailable']</value>
      <webElementGuid>5704132c-bd44-4588-ad12-d90eef03c044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/section/div/div/input[5]</value>
      <webElementGuid>1f703001-67b6-43d5-bcbe-3d26921f80aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>d47df723-cd06-4f0e-b03d-cb354461cd2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'refund_for_unavailable' and @id = 'refund_for_unavailable' and @type = 'radio']</value>
      <webElementGuid>4c7b5509-836b-4abe-8e50-c046bcea6b3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
