<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Instant Mix</name>
   <tag></tag>
   <elementGuidId>bcb96c0a-bda6-4861-87f5-6bfba9cc9992</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main-menu']/li/div/ul/li[11]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(11) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81a8d1bb-b276-4182-9ae6-906d7e470b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.vrajfresh.com/category/instant-mix</value>
      <webElementGuid>21b849a3-8227-43f9-b373-04465d1e4ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instant Mix</value>
      <webElementGuid>73e83df4-9e34-4b8a-9325-f9af3b4be068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-menu&quot;)/li[1]/div[@class=&quot;submenu&quot;]/ul[1]/li[11]/a[1]</value>
      <webElementGuid>70d34a33-d4f7-4fec-9a8e-38757b35f441</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main-menu']/li/div/ul/li[11]/a</value>
      <webElementGuid>ec12a9d6-d758-4416-8bc8-cffaca845d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Instant Mix')]</value>
      <webElementGuid>06bbb105-7446-4525-ad5d-e71cb7642ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salt Sugar &amp; Jaggery'])[1]/following::a[1]</value>
      <webElementGuid>037cebf0-51b2-4ce5-8655-c596284da83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rice'])[1]/following::a[2]</value>
      <webElementGuid>7de0af51-cfa7-4d1e-aba6-407b898bdbd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Flour'])[1]/preceding::a[1]</value>
      <webElementGuid>196aa8d8-c93d-483e-b51b-b2342999d430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canned Food'])[1]/preceding::a[2]</value>
      <webElementGuid>586dd509-fe1e-4bdf-9bd6-8ab99d2ac1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Instant Mix']/parent::*</value>
      <webElementGuid>0ac6fffa-3f75-4037-8a63-eba25e9581a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.vrajfresh.com/category/instant-mix')]</value>
      <webElementGuid>9f62ef66-dda8-4a6b-b3b3-4b3c3ebfb347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a</value>
      <webElementGuid>dffb99b6-6f2b-4a3c-92ba-491830e7e847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.vrajfresh.com/category/instant-mix' and (text() = 'Instant Mix' or . = 'Instant Mix')]</value>
      <webElementGuid>c3ba60bd-70c1-4636-90d5-52c2323136cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
