<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Frozen_but</name>
   <tag></tag>
   <elementGuidId>fd0d7a77-3bfa-4176-90a9-85cb91470f58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main-menu']/li[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > button.but</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>12741b43-0613-4943-a606-61ea39989bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>but</value>
      <webElementGuid>6469f7e9-31e5-47b5-8c68-69c2aebb1a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-menu&quot;)/li[3]/button[@class=&quot;but&quot;]</value>
      <webElementGuid>f96f88b2-429d-4b5a-b026-abe64b1f557c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main-menu']/li[3]/button</value>
      <webElementGuid>79b21e1d-cf29-49bd-bf05-fc188d9ac85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button</value>
      <webElementGuid>1b4e2865-d574-4d9a-adbf-25e767a88d54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
