<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add_1</name>
   <tag></tag>
   <elementGuidId>08ccc83c-8471-48d0-b4b3-ac8193e6e99a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_1512']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_1512</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6fb60516-6e49-44e4-9755-8502c75df135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_1512</value>
      <webElementGuid>77e6dbe0-b5dd-4eb4-a19f-d4a753d397cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add_cart </value>
      <webElementGuid>1536ac41-e051-46d9-8fe8-f58737fa2e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isperisible</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>183594a5-aa82-4461-9d9e-c680bb0fad62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productslug</name>
      <type>Main</type>
      <value>gits-gulab-jamun</value>
      <webElementGuid>4471476a-fe85-45b2-842f-c60b2a625fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productimage</name>
      <type>Main</type>
      <value>https://www.vrajfresh.com/admin/uploads/products/7092C9DC-8102-4305-82C2-18369CC7E0CB.jpg</value>
      <webElementGuid>0c22431e-8695-414d-a037-cf1dd73df8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productname</name>
      <type>Main</type>
      <value>Gits Gulab Jamun</value>
      <webElementGuid>4056637d-a1b8-47b3-92b0-3d5b1e24cc7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>1.99</value>
      <webElementGuid>194fc3bf-e47f-46a2-87cc-9c4c07dabf2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productid</name>
      <type>Main</type>
      <value>1512</value>
      <webElementGuid>f39cd774-c491-4bc7-9000-dd30f25676fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productweight</name>
      <type>Main</type>
      <value>0.22</value>
      <webElementGuid>f35040e4-e825-4fc9-94ea-532d1f8f3b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-producttax</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a1db1438-e7bb-4961-8a74-a42c20059339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>59dbd06a-4fd3-457d-b9fd-cbb20b2f62d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_1512&quot;)</value>
      <webElementGuid>ae77b1dd-977c-407b-be46-a5b3464580d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_1512']</value>
      <webElementGuid>df0ccac7-a0cc-4c37-b301-d004e740bd99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_product']/div/div/ul/li[2]/button</value>
      <webElementGuid>f12e3238-4dd4-4125-b99b-e85bc751f53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::button[1]</value>
      <webElementGuid>33d6f578-9461-4d7d-85d3-b72b38419049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::button[2]</value>
      <webElementGuid>6466eb42-bcc9-4e07-92fd-0d1f62e3361b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@vrajfresh.com'])[1]/preceding::button[1]</value>
      <webElementGuid>b2ad82f2-d2f8-458d-9ee7-c2601fcf1b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>0f708179-301f-44fe-b574-0c4c5c6a217c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[2]/button</value>
      <webElementGuid>3f009172-192f-4d6e-b71d-46dbac33e491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_1512' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>47e49646-b996-495c-a380-c1ac54f3ad77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
