<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>12fa7403-8360-4cf4-9e46-a80060e4b40e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='category_product']/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.product-box > a > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2bb8bee6-be2a-4e7a-a6e5-af1974e0ec91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.vrajfresh.com/admin/uploads/products/7092C9DC-8102-4305-82C2-18369CC7E0CB.jpg</value>
      <webElementGuid>8e1526a0-8ac1-40e3-a771-c4e13de1e64d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.src=&quot;https://www.vrajfresh.com/admin/uploads/logo-2.png&quot;</value>
      <webElementGuid>d6ff02ac-a07c-4e1d-a21d-702a4743845f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_product&quot;)/div[@class=&quot;product-box&quot;]/a[1]/img[1]</value>
      <webElementGuid>08912e5e-b060-46a4-ba6d-4104008579f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_product']/div/a/img</value>
      <webElementGuid>cb5d7ef0-377b-4e4c-85b1-4fd5e82a7961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.vrajfresh.com/admin/uploads/products/7092C9DC-8102-4305-82C2-18369CC7E0CB.jpg')]</value>
      <webElementGuid>c07a7642-57e1-4d8e-a410-00690e62a8da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>6d7da7c6-cf06-4822-8796-46219f8c639c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.vrajfresh.com/admin/uploads/products/7092C9DC-8102-4305-82C2-18369CC7E0CB.jpg']</value>
      <webElementGuid>19d0fadc-15f9-46dc-a06e-2e7a22bcc40f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
