<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_2.00lb - 4.003.00lb - 5.00</name>
   <tag></tag>
   <elementGuidId>81edc3d1-2f82-4541-b6b7-d7e75b810e70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='jumpMenu'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>851bba1d-8db5-4ae4-908a-21b600c730f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumpMenu</value>
      <webElementGuid>fe453177-7634-4bde-960b-9d3d2b6e4f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jumpMenu</value>
      <webElementGuid>2e76737c-3431-4cec-8e44-0ff1f66508aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>variants </value>
      <webElementGuid>58014074-057b-46fb-88ad-8d34c83732a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2.00lb - $4.003.00lb - $5.00</value>
      <webElementGuid>0549c386-e245-4cc3-ba09-c0acea97c7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_product&quot;)/div[@class=&quot;product-box&quot;]/div[1]/form[@id=&quot;form&quot;]/select[@id=&quot;jumpMenu&quot;]</value>
      <webElementGuid>73eb19d1-0851-4ca7-acba-9a2421f4483a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='jumpMenu'])[2]</value>
      <webElementGuid>34c2905f-ee28-4664-a3f2-1273c8320c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='form']/select)[2]</value>
      <webElementGuid>d2ecee35-7604-4891-ad23-cf97df8052d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='vadilal Pista Ice cream'])[1]/following::select[1]</value>
      <webElementGuid>c9dce2c0-3884-4563-b58b-db0a0083397d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::select[1]</value>
      <webElementGuid>0348e4fe-d59d-4195-a10d-5035865f9350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/preceding::select[1]</value>
      <webElementGuid>e36c3eb5-d35a-4aa5-b929-ec9bb2d26c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[2]/preceding::select[1]</value>
      <webElementGuid>c0ac2984-b50d-43d3-8cd2-c6ac7ef81f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/select</value>
      <webElementGuid>acefc381-bd0e-41f5-b4ff-5595cfe634cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jumpMenu' and @id = 'jumpMenu' and (text() = '2.00lb - $4.003.00lb - $5.00' or . = '2.00lb - $4.003.00lb - $5.00')]</value>
      <webElementGuid>7f65bf96-0553-43a7-b481-bff275ae8301</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
