<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_6.29</name>
   <tag></tag>
   <elementGuidId>f0581dc2-976c-426f-b577-ed1cdc36053b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cart-total']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cart-total</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>49f5c4e5-8d4f-4a0f-8dff-edbd576d38ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart-total</value>
      <webElementGuid>5be04486-985f-40ce-a2ce-f4d650940c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-total</value>
      <webElementGuid>e792451f-e93d-40a0-9d2e-45cdc7bfe864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6.29</value>
      <webElementGuid>51bbd85c-6bfa-4a31-a0c0-e0ecc519ae3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-total&quot;)</value>
      <webElementGuid>c2bffe6f-84e9-47ec-b9a1-cd153bd608a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cart-total']</value>
      <webElementGuid>745c4218-ef86-4f2c-86d3-5d5b9ec70087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/section/div/div[2]/div/ul/li[10]/span/b/span</value>
      <webElementGuid>54d360bd-3488-459f-8ce4-c58b289831df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/preceding::span[1]</value>
      <webElementGuid>388411d0-4b14-4656-942e-208910299132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceed to Pay'])[1]/preceding::span[1]</value>
      <webElementGuid>62b9c093-0ce0-4cb5-9ef4-e4cb51754e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6.29']/parent::*</value>
      <webElementGuid>7d4625da-a293-4aa0-bce0-a36f561e8fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/span/b/span</value>
      <webElementGuid>ba36a037-4474-4a0a-a1a6-b7f44d17b27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@name = 'cart-total' and @id = 'cart-total' and (text() = '6.29' or . = '6.29')]</value>
      <webElementGuid>a4847448-3887-4afe-b258-10e295cc8992</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
