<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Tip</name>
   <tag></tag>
   <elementGuidId>40dde8de-ee45-4636-843c-a32f1c3ce5b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add_tip_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='add_tip_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8be56406-1343-4457-971e-c20b81be2364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void();</value>
      <webElementGuid>0dfc1f90-cbed-4eaa-9564-647dfc31ce42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addCustomTipAmount()</value>
      <webElementGuid>aaf44a3b-55a5-41be-9e52-8fae06b745de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add_tip_button</value>
      <webElementGuid>0657e7fc-5ff0-440c-8680-c192e2d47d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Tip</value>
      <webElementGuid>dd627610-43aa-4e9d-b1e0-c3c52c1e401a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add_tip_button&quot;)</value>
      <webElementGuid>812b4ac7-12a9-4d0e-afc0-9d20e24e0827</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='add_tip_button']</value>
      <webElementGuid>6fbd63cc-2dee-403e-909e-149e4667c743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/section/div/div/div[11]/a</value>
      <webElementGuid>2e53c1c9-5c18-4701-ac82-dc5be1e60372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Tip')]</value>
      <webElementGuid>048436ad-0fba-403e-94d9-103c093224e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter valid amount'])[1]/following::a[1]</value>
      <webElementGuid>fdc62b43-1ff2-4fa2-ac1b-3271fb634ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Tip'])[1]/following::a[1]</value>
      <webElementGuid>3f6129b8-aeb2-42fb-b784-2e90b1f4091a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove Tip'])[1]/preceding::a[1]</value>
      <webElementGuid>179b4fa8-5603-431b-a3fa-d5586192194e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Notes (optional)'])[1]/preceding::a[2]</value>
      <webElementGuid>604d684a-2ddc-40e6-a7a5-35ef721dda36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Tip']/parent::*</value>
      <webElementGuid>1a79b021-bf2e-47f7-84e4-4cf9964afc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void();')]</value>
      <webElementGuid>56ed6312-4ddf-4078-90df-731841260ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/a</value>
      <webElementGuid>1a8bd9cf-8ff7-4097-a468-6c796aecd32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void();' and @id = 'add_tip_button' and (text() = 'Add Tip' or . = 'Add Tip')]</value>
      <webElementGuid>0ad9073b-fa81-458d-b673-887fe9afca5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
