<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Proceed to checkout</name>
   <tag></tag>
   <elementGuidId>954067db-2929-4baa-895c-eeaac16554ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vraj-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='vraj-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>38a06a11-6df9-4e74-b4a3-f7ddc47c8d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/front/checkout</value>
      <webElementGuid>9788dfc5-90a0-45e6-8be0-0c6214352fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vraj-btn</value>
      <webElementGuid>005b9033-dc96-4cad-89a4-0977ea890ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vraj-btn</value>
      <webElementGuid>58c7d3f9-fbfd-47fd-b3cf-e90665398e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed to checkout </value>
      <webElementGuid>12a7b9b3-5ef7-47b3-8e47-b4af895aac47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vraj-btn&quot;)</value>
      <webElementGuid>c8b2e498-c68f-4c12-b190-5f702d94fa58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='vraj-btn']</value>
      <webElementGuid>22b4fa96-5f05-4f88-aa23-f45347a99d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Proceed to checkout')]</value>
      <webElementGuid>023b23fe-4fc4-445c-8613-697b2084e3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes, We deliver in your area!'])[2]/following::a[1]</value>
      <webElementGuid>16d69d00-d52a-4f8a-b90d-4b957c4f8eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$43.9'])[2]/following::a[1]</value>
      <webElementGuid>f9992757-4b7b-4720-93ea-480c145744d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@vrajfresh.com'])[1]/preceding::a[2]</value>
      <webElementGuid>9defb696-91a5-4443-908e-e2eb2174f527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proceed to checkout']/parent::*</value>
      <webElementGuid>054ead27-0008-48dd-8531-f157f204eb30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dev.thcitsolutions.com/vrajfresh/front/checkout')]</value>
      <webElementGuid>c9f73509-7d40-436b-8421-6c1b4beff446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>cb760ade-33a6-47ea-85ea-a79ae6e94db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev.thcitsolutions.com/vrajfresh/front/checkout' and @id = 'vraj-btn' and (text() = 'Proceed to checkout ' or . = 'Proceed to checkout ')]</value>
      <webElementGuid>25486627-6c65-467a-9f3a-c5667f27266d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
