<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Custom Tip</name>
   <tag></tag>
   <elementGuidId>f9f51746-c6a5-4275-8ec9-93ebbc761ece</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order_tip_custom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='order_tip_custom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e00cacc7-728c-4037-b23d-26c6b916ace8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_tip_custom</value>
      <webElementGuid>09fd0b74-a74f-4211-a33e-176a715daf59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b844deae-dd81-4542-81ed-8ff57e169f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>f67ffaf4-5c98-4942-9511-a813bfe22dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tip</name>
      <type>Main</type>
      <value>custom</value>
      <webElementGuid>7393cad1-c8bc-46dc-9503-d0f301e59506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addCustomTip();</value>
      <webElementGuid>863a458f-62b2-4076-a977-590d74687f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Custom Tip </value>
      <webElementGuid>cd45e387-211e-48f4-b33d-170582ed0f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_tip_custom&quot;)</value>
      <webElementGuid>c50a9313-eaf3-4fc9-844c-6449628a991b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='order_tip_custom']</value>
      <webElementGuid>0c566eb5-c4df-4da7-8757-4fc93b809067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/section/div/div/div[11]/button[6]</value>
      <webElementGuid>f72a95bb-66ca-4704-8513-6222c0cf042a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 25'])[1]/following::button[1]</value>
      <webElementGuid>438ec534-b65a-4753-a5c8-c89cc55beacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 20'])[1]/following::button[2]</value>
      <webElementGuid>66547924-3a2a-49ec-af1a-81b1d4a4229e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter valid amount'])[1]/preceding::button[1]</value>
      <webElementGuid>27324f9f-2177-4b12-bcb8-87ae403d7a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Tip'])[1]/preceding::button[1]</value>
      <webElementGuid>34dcc445-ee42-4421-80a9-e3ad373fd149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Custom Tip']/parent::*</value>
      <webElementGuid>a7564cb0-c635-4734-bef3-1e8bb39c6a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[6]</value>
      <webElementGuid>9ff3692e-1bc2-425b-ae13-c16355d2ebef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'order_tip_custom' and @type = 'button' and (text() = 'Custom Tip ' or . = 'Custom Tip ')]</value>
      <webElementGuid>686f5dcb-2bd1-451a-a823-05b958e66573</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
