<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes, please substitute unavailable it_302eac</name>
   <tag></tag>
   <elementGuidId>63b8d2f3-94f8-4c29-b3d5-f415d5d40cf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#refund_for_unavailable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refund_for_unavailable']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4888a700-2a4e-4809-ae43-aa2068c3d603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refund_for_unavailable</value>
      <webElementGuid>0079206a-9f19-4365-9c33-dbf96a56c4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refund_for_unavailable</value>
      <webElementGuid>27e7dd56-3952-4745-8a87-1ab332886653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b522ab78-75d1-4fff-910a-40fe7ceb323f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>03525639-1405-45fe-a8ea-93159ea3870a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refund_for_unavailable&quot;)</value>
      <webElementGuid>52ae64d6-a679-4fe4-89ab-9bb9469138e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refund_for_unavailable']</value>
      <webElementGuid>ff170045-25b7-4be8-b628-2ed138a9ea79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/section/div/div/input[5]</value>
      <webElementGuid>59ac3f51-f73e-4319-89be-1933eb6d5e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>6152e16c-1a45-4f5d-8ffa-fb1197591bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'refund_for_unavailable' and @id = 'refund_for_unavailable' and @type = 'radio']</value>
      <webElementGuid>6065a598-ad76-49d2-8450-792c927e8349</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
