<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Custom Tip_tip_amount</name>
   <tag></tag>
   <elementGuidId>2f32fe29-bdb6-4c34-8dfe-5b58ef14420a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tip_amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tip_amount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>955f9a11-786b-480b-be43-3bcae78c76ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Tip Amount</value>
      <webElementGuid>1bbfd6de-00e3-4726-986f-fa08c5b995fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tip_amount</value>
      <webElementGuid>f122f135-ff75-4dde-a61d-bfdd34c81520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tip_amount</value>
      <webElementGuid>0228353e-6057-4486-bd95-1fa0f33a8073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57dee886-3da0-4ff6-8e7f-b679045295d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isNumber(event)</value>
      <webElementGuid>b7773569-04b9-46ef-b03c-2204a2cea0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tip_amount&quot;)</value>
      <webElementGuid>ed9f3308-b28c-4a1b-adb9-bbebdb8e521e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tip_amount']</value>
      <webElementGuid>d4e5db38-033e-43af-be7d-41cdd1962143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/section/div/div/div[11]/input</value>
      <webElementGuid>96890766-cf99-4e14-aed7-fef08a009736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>e00d7352-939c-4418-b785-ee52fe2e29e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Tip Amount' and @name = 'tip_amount' and @id = 'tip_amount' and @type = 'text']</value>
      <webElementGuid>30c26f5e-2f23-449e-b5e8-e0f6db44a174</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
