<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_X_coupon_code</name>
   <tag></tag>
   <elementGuidId>382f2fa9-6403-4ed1-864d-9f3f06a1bf64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coupon_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='coupon_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>781c0772-58e2-4c1a-a3e7-c7dcafd60c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>coupon_code</value>
      <webElementGuid>37b33565-99f8-429a-aab4-99da4e019b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Coupon Code</value>
      <webElementGuid>65762a79-b69f-4944-8707-ee99b0c58927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16f06c5b-e009-45fd-ab39-44ca88e2d3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coupon_code</value>
      <webElementGuid>3345c824-50af-4edc-b253-68ab28cfbf93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coupon_code&quot;)</value>
      <webElementGuid>972c5a57-dec2-406d-a7f2-f7e091ad1e66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='coupon_code']</value>
      <webElementGuid>e4fa92c2-4729-44b5-bc4a-4b114bd6f049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/form/input</value>
      <webElementGuid>44770553-caea-4e90-8977-40f07beee8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'coupon_code' and @placeholder = 'Coupon Code' and @type = 'text' and @id = 'coupon_code']</value>
      <webElementGuid>0b835859-efe2-44a5-8fc6-2672199c5100</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
