<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_2.00lb - 4.003.00lb - 5.00</name>
   <tag></tag>
   <elementGuidId>159eb76e-b6ed-4df3-a977-b311f8628cdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='jumpMenu'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>583dc2ee-9125-4f53-a898-086db2ddda00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumpMenu</value>
      <webElementGuid>ebe16746-6a69-48a0-adac-658c55ccef8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jumpMenu</value>
      <webElementGuid>912ef2e5-2f98-4364-8500-5090b42c2f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>variants </value>
      <webElementGuid>b83a866b-81b7-4bc5-8420-9d7f71e83201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2.00lb - $4.003.00lb - $5.00</value>
      <webElementGuid>0e725732-1974-45b2-a3d8-f276378702d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_product&quot;)/div[@class=&quot;product-box&quot;]/div[1]/form[@id=&quot;form&quot;]/select[@id=&quot;jumpMenu&quot;]</value>
      <webElementGuid>d8b83654-5c98-47ad-92fc-00cc50a55ad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='jumpMenu'])[2]</value>
      <webElementGuid>b2908a9b-214a-4d39-b676-ea55dcd8d95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='form']/select)[2]</value>
      <webElementGuid>23d245e8-5589-4630-821b-8390d3541b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='vadilal Pista Ice cream'])[1]/following::select[1]</value>
      <webElementGuid>cba93b89-035c-4a46-b0f7-d2d495470f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::select[1]</value>
      <webElementGuid>a4d45310-7b03-4c1d-aa40-7037c4ac48ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/preceding::select[1]</value>
      <webElementGuid>ebd7c93f-f2ac-47ac-9aa9-f3d496f9d9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[2]/preceding::select[1]</value>
      <webElementGuid>97ea6504-9f0f-402c-be43-12077a336019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/select</value>
      <webElementGuid>6693d674-49a3-42de-bfab-bc2574a5be44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jumpMenu' and @id = 'jumpMenu' and (text() = '2.00lb - $4.003.00lb - $5.00' or . = '2.00lb - $4.003.00lb - $5.00')]</value>
      <webElementGuid>23fc1c10-1417-4c52-857f-6c089fc06369</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
