<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_26.29</name>
   <tag></tag>
   <elementGuidId>57f225e3-4fcd-4053-9573-b665ffccb231</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-total</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cart-total']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cb3420ed-9145-4ad0-bcfe-4834d1ca2c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart-total</value>
      <webElementGuid>1531116c-26b4-4c7d-a56f-343653b3390d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-total</value>
      <webElementGuid>d54908f7-3541-47d6-9d3b-ac9c260a66ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>26.29</value>
      <webElementGuid>517b1929-0591-4ddb-9c47-e632148539d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-total&quot;)</value>
      <webElementGuid>09d208be-d4c2-4a3b-ba46-2b0e0e6972ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cart-total']</value>
      <webElementGuid>06dde88f-574d-4568-97d0-0bc3debfd6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/section/div/div[2]/div/ul/li[10]/span/b/span</value>
      <webElementGuid>fb02ff0f-cd04-4dc7-aeec-e5f91104102b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/preceding::span[1]</value>
      <webElementGuid>40ff76ce-449b-481a-a0a0-52c6a86dfea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceed to Pay'])[1]/preceding::span[1]</value>
      <webElementGuid>a48d4f82-90ce-4e55-9816-220617911cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='26.29']/parent::*</value>
      <webElementGuid>ea0dc336-8acc-446e-903a-32c7b71bdbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/span/b/span</value>
      <webElementGuid>06fba2f7-9fdf-44bb-a93f-c9b31b815c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@name = 'cart-total' and @id = 'cart-total' and (text() = '26.29' or . = '26.29')]</value>
      <webElementGuid>e488ec5e-b375-4620-a5ec-1b68e4f9ce0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
