<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_46.28</name>
   <tag></tag>
   <elementGuidId>bd09176e-0fe3-4ddb-bd88-ef508f08307b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-total</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cart-total']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>41d0a136-6e46-490b-a4f5-2de1a1575c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart-total</value>
      <webElementGuid>f83aa004-e132-4335-9cfa-1abedf1fb4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-total</value>
      <webElementGuid>87231cfb-5ed0-4003-9747-06812b917ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>46.28</value>
      <webElementGuid>aa680651-4cd1-49c3-9580-fd5ce5051213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-total&quot;)</value>
      <webElementGuid>4f606f01-14ed-4ec0-bccc-22756d2b1aa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cart-total']</value>
      <webElementGuid>18ecfe51-ffe8-436d-9c36-479edde42f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/section/div/div[2]/div/ul/li[10]/span/b/span</value>
      <webElementGuid>9769b0b1-3d8e-4fb8-be0c-720722a8742b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/preceding::span[1]</value>
      <webElementGuid>dd42b9d9-d0fe-4b5f-8797-8d7e2f203873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceed to Pay'])[1]/preceding::span[1]</value>
      <webElementGuid>07cff5bc-1dd6-4166-bd65-ff20dbbf6ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='46.28']/parent::*</value>
      <webElementGuid>67de207c-a3dd-4619-95c0-7d6013a94a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/span/b/span</value>
      <webElementGuid>bc53cf5c-477a-4868-8314-f49a9812578c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@name = 'cart-total' and @id = 'cart-total' and (text() = '46.28' or . = '46.28')]</value>
      <webElementGuid>f6a14fbf-6706-42c7-b0e3-15b158b2bd2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
