<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Remove Tip</name>
   <tag></tag>
   <elementGuidId>12149038-a859-4894-976b-b9a23e4e8f8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tip_remove_button > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='removeTipAmount()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>133ae8e4-c193-480f-995b-a3b2f27f5ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>f3654ea4-6aa7-42ca-a081-745410e24024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>removeTipAmount()</value>
      <webElementGuid>de776000-e0b2-4f64-afe3-c148dee32f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove Tip</value>
      <webElementGuid>c34fbada-3430-44c8-aa73-8473bbb09e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tip_remove_button&quot;)/a[1]</value>
      <webElementGuid>4a55d3e6-c7cb-44c8-a6f3-5b344d90f0a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='removeTipAmount()']</value>
      <webElementGuid>d9020abe-86ec-4abe-a759-a993e604ebe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='tip_remove_button']/a</value>
      <webElementGuid>1360d82f-9dce-4371-a3f6-32c59010f63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Remove Tip')]</value>
      <webElementGuid>9c247842-fadc-4e1c-8f60-e0a1b35c0f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Tip'])[1]/following::a[1]</value>
      <webElementGuid>a7a814cd-7b29-4557-a18f-80a10198d408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter valid amount'])[1]/following::a[2]</value>
      <webElementGuid>4cc7ed35-adbb-42be-86d4-8197df108465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Notes (optional)'])[1]/preceding::a[1]</value>
      <webElementGuid>19ea6aeb-788c-4a5a-b6d6-2ed01b86f6e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remove Tip']/parent::*</value>
      <webElementGuid>a62bb56d-2c50-4521-b4ab-5e38faa49014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>9a3774e8-a354-4327-a1e3-e651acd321d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>b02de236-33ac-462f-bdbd-9dacd19e07cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Remove Tip' or . = 'Remove Tip')]</value>
      <webElementGuid>4a5e9840-ea75-4f4b-9dc6-5f57a736f657</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
