<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add_1_2_3</name>
   <tag></tag>
   <elementGuidId>d8d08c20-1465-43ca-a28c-023c4d0da4f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_7127</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_7127']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>920eb3ca-8604-429e-b880-d615a4679926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_7127</value>
      <webElementGuid>04f4c7dc-06bc-43ce-a6bb-554d525fe37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add_cart </value>
      <webElementGuid>31b1d7a0-5a2f-4cb1-be95-12fb52588093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isperisible</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>29dc5f93-c9d3-42e0-989f-8a690bc4f206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productslug</name>
      <type>Main</type>
      <value>parle---s</value>
      <webElementGuid>7105d83e-8ba4-4469-b201-f5ff7c9cddc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productimage</name>
      <type>Main</type>
      <value>https://www.vrajfresh.com/admin/uploads/products/</value>
      <webElementGuid>c6b46136-2694-4b43-a51a-1c47a0203adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productname</name>
      <type>Main</type>
      <value>Parle - s</value>
      <webElementGuid>e9102d79-fecc-478a-9630-521d713f48bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>3.00</value>
      <webElementGuid>d12bc999-cefc-4413-88a6-6f085b352d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productid</name>
      <type>Main</type>
      <value>7127</value>
      <webElementGuid>6e37e778-98de-4e74-8b5c-0170e9c56c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productweight</name>
      <type>Main</type>
      <value>2.00</value>
      <webElementGuid>879bd01f-b8ae-4344-82e5-6adce7fef178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-producttax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>011fd983-ac9c-4508-b53a-284ed4245f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>b280d305-4a11-46b3-b27b-f6044c15c022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_7127&quot;)</value>
      <webElementGuid>96a42604-d949-478a-aa02-fe2abb3dc76d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_7127']</value>
      <webElementGuid>9f56a6d8-d5e6-43cd-9dda-ea42b2ac18d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_product']/div[3]/div/ul/li[2]/button</value>
      <webElementGuid>e45ee68e-4424-4bc8-9e9d-7099c4efb08d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[3]/following::button[1]</value>
      <webElementGuid>45a0ca2c-d1fe-4e75-b7e7-0a2d6d79d24e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3]/following::button[2]</value>
      <webElementGuid>bfde3419-ecfd-4f30-b275-1c66e3019007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[2]/button</value>
      <webElementGuid>6eb19dfb-c737-4802-871a-b2297e736189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_7127' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>6bff7ee0-8b80-4038-8707-1d107f4318a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
