<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>f45b85f5-6ebc-4a93-b96c-ceccd27b92d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://www.vrajfresh.com/assets/images/cart-icon.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>413553f4-772c-4973-96bf-5de194a65a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.vrajfresh.com/assets/images/cart-icon.png</value>
      <webElementGuid>b0d627c7-f460-4afa-89a6-d4455fd6d23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[1]/div[@class=&quot;container container-flex header&quot;]/div[@class=&quot;my-account&quot;]/ul[1]/li[2]/a[1]/img[1]</value>
      <webElementGuid>456ba916-bbdf-410b-a458-90a7beec2a55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.vrajfresh.com/assets/images/cart-icon.png')]</value>
      <webElementGuid>c84749d5-106c-4fec-9cfa-80cd36a635d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>af717204-91f5-44db-a2ce-2a12a32ac10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.vrajfresh.com/assets/images/cart-icon.png']</value>
      <webElementGuid>31b0f1d4-b625-481c-8f81-11877670d19c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
