<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1 (1)</name>
   <tag></tag>
   <elementGuidId>7d90f59a-35f5-4712-a599-7761390baf0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form > button.header_button > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-autocomplete']/form/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9c99e5ce-59df-40a1-9530-9ec18f69d77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.vrajfresh.com/assets/images/search-icon.png</value>
      <webElementGuid>a284e8da-c3de-4edb-9be9-3ab347c1f028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-autocomplete&quot;)/form[1]/button[@class=&quot;header_button&quot;]/img[1]</value>
      <webElementGuid>aaf54dbf-901d-4f21-b6eb-8572f6a9d164</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-autocomplete']/form/button/img</value>
      <webElementGuid>03724cc6-b7e5-40d4-8637-fb78dbf44a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.vrajfresh.com/assets/images/search-icon.png')]</value>
      <webElementGuid>2fb21fac-0b79-40e8-9e99-9f224a665678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/img</value>
      <webElementGuid>6b986151-42b8-4837-9ab9-f6eda4e28e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.vrajfresh.com/assets/images/search-icon.png']</value>
      <webElementGuid>e967b86b-200f-42b0-a3ee-0367f43445d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
