<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_X_coupon_code</name>
   <tag></tag>
   <elementGuidId>d4c2f229-1b91-4646-b1f3-82837c677861</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coupon_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='coupon_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7985a5d6-04cc-4059-abe1-28e7dc75b3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>coupon_code</value>
      <webElementGuid>1fb09f52-b6b7-4cb8-ace5-341ca00fa9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Coupon Code</value>
      <webElementGuid>de45455b-0c75-4b22-9c65-bba8782cf7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4bdb757c-e08f-4645-b959-f4a9fa95b72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coupon_code</value>
      <webElementGuid>9bc4f055-3261-423a-8378-19cc302b89aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coupon_code&quot;)</value>
      <webElementGuid>825eda09-a6ce-4540-91dd-f2bd8b15f718</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='coupon_code']</value>
      <webElementGuid>84d2bef6-f2ac-475c-a7af-1b68eb00b7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/form/input</value>
      <webElementGuid>d74b78aa-33b1-4be2-9e3b-f0b1075a7fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'coupon_code' and @placeholder = 'Coupon Code' and @type = 'text' and @id = 'coupon_code']</value>
      <webElementGuid>86aa37bd-935c-44bf-8e23-a5183fc34e98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
