<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_2.00lb - 4.003.00lb - 5.00</name>
   <tag></tag>
   <elementGuidId>3c41dce5-5219-4122-9933-59796b7b6be3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='jumpMenu'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>695204d0-c1c4-4a9e-b3f3-d6f6b49fdf06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumpMenu</value>
      <webElementGuid>b5881e56-3b72-4c41-8dac-afb4f2384220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jumpMenu</value>
      <webElementGuid>2938b01e-43bf-462b-9386-65fcb9dfc7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>variants </value>
      <webElementGuid>efddc7c9-533a-4ad9-838a-d66f2d5adb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2.00lb - $4.003.00lb - $5.00</value>
      <webElementGuid>65192905-5fc7-4ba0-84b2-8ba6521c58f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_product&quot;)/div[@class=&quot;product-box&quot;]/div[1]/form[@id=&quot;form&quot;]/select[@id=&quot;jumpMenu&quot;]</value>
      <webElementGuid>be167e7d-00a7-4e4f-b476-f6c8d25d6ff7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='jumpMenu'])[2]</value>
      <webElementGuid>e60c1d7a-8c71-475e-826a-653725e94e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='form']/select)[2]</value>
      <webElementGuid>335ba971-d65a-457b-85e3-9f00cad53270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='vadilal Pista Ice cream'])[1]/following::select[1]</value>
      <webElementGuid>5b758711-2c0d-42f0-bd25-dfe7428aa477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::select[1]</value>
      <webElementGuid>b47d81e9-74db-49d4-8695-1a0bf9e155df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/preceding::select[1]</value>
      <webElementGuid>9df66b3a-702c-4f00-9033-d0df07822798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[2]/preceding::select[1]</value>
      <webElementGuid>fe358543-5d81-48c0-b890-3cff30402850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/select</value>
      <webElementGuid>f784358c-77eb-48ac-8f50-4ee8de186ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jumpMenu' and @id = 'jumpMenu' and (text() = '2.00lb - $4.003.00lb - $5.00' or . = '2.00lb - $4.003.00lb - $5.00')]</value>
      <webElementGuid>d0dfe25a-e860-4671-be7c-4de5a5963413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
