<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_14.29</name>
   <tag></tag>
   <elementGuidId>0e7395e2-05f5-44be-acc4-a9aa76bf17f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-total</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cart-total']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ac456a51-a34f-45e5-99fb-9fb1fedf8a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart-total</value>
      <webElementGuid>13edb28b-7855-4631-a126-3b0e03e3c0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-total</value>
      <webElementGuid>56bbb788-8dc3-4271-930c-b43efa7f68bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>14.29</value>
      <webElementGuid>e7060d80-89a8-4d1b-a04b-add87369fcfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-total&quot;)</value>
      <webElementGuid>076d1c3b-2f75-47a6-a95a-9ec4d5899c4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cart-total']</value>
      <webElementGuid>a1552687-f657-40dd-b31a-7142df9c1b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/section/div/div[2]/div/ul/li[10]/span/b/span</value>
      <webElementGuid>149a7340-dd1e-4684-8ed4-efe95c1cf6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/preceding::span[1]</value>
      <webElementGuid>5ff065ff-4ede-43e8-875a-72a16a3b2d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceed to Pay'])[1]/preceding::span[1]</value>
      <webElementGuid>9f87c763-79b7-4c23-92b9-d3cd8aec06a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='14.29']/parent::*</value>
      <webElementGuid>a7c5f4b9-457f-4f94-8072-fd5d28dc43f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/span/b/span</value>
      <webElementGuid>08f0b154-b4f0-439e-b5d6-4d79683c2315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@name = 'cart-total' and @id = 'cart-total' and (text() = '14.29' or . = '14.29')]</value>
      <webElementGuid>ea8befc4-63e2-41da-9ceb-bcafd1c2d7c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
