<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add (1)</name>
   <tag></tag>
   <elementGuidId>5ef24533-ff21-4a07-a7ca-30716cfd1cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_6271</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_6271']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d1fe8ad-8697-4c9c-8353-ebe1a5c0f6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_6271</value>
      <webElementGuid>93d9bc5f-ccf1-4b01-b70b-da8dd3c4afa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add_cart </value>
      <webElementGuid>ebc8c0b2-7289-4549-b064-ead5d0353f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isperisible</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>db59112f-8b2f-49f2-a0ff-8bf33a3464a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productslug</name>
      <type>Main</type>
      <value>kawan-flakey-paratha</value>
      <webElementGuid>537a1af9-b3dd-4b89-b0d4-0edf7679f729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productimage</name>
      <type>Main</type>
      <value>https://dev.thcitsolutions.com/vrajfresh/admin/uploads/products/18169258-724E-44B2-A029-EC07C923400D.jpg</value>
      <webElementGuid>dcedab29-a292-447d-ac34-6c82dbc454bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productname</name>
      <type>Main</type>
      <value>Kawan Flakey Paratha</value>
      <webElementGuid>2fcff93e-de89-491f-82ae-48eb6b96e08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>3.99</value>
      <webElementGuid>ea73c50e-3666-4c66-9029-26a20693a0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productid</name>
      <type>Main</type>
      <value>6271</value>
      <webElementGuid>4f4abfc1-64f6-4964-92f2-bd5d5fac28c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productweight</name>
      <type>Main</type>
      <value>5.00</value>
      <webElementGuid>7588b5ae-b031-4a49-a833-f8a92584a1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-producttax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1cd0aa6d-f848-4cd1-a8ef-eb3687d708a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>3ac5d6f5-d044-4941-b10b-6208899ae2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_6271&quot;)</value>
      <webElementGuid>64ed898d-c528-4ff1-a64b-ef70161c919d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_6271']</value>
      <webElementGuid>a8ab6b0c-c3eb-473f-a21f-bb57b92c85d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_product']/div/div/ul/li[2]/button</value>
      <webElementGuid>c154a585-ee29-450e-b56e-d02bc9237146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::button[1]</value>
      <webElementGuid>07a72f14-3f8a-46e2-a803-c68750d6faba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::button[2]</value>
      <webElementGuid>e5e01b6b-c6c4-4199-ac33-a6e63b1c1166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@vrajfresh.com'])[1]/preceding::button[1]</value>
      <webElementGuid>27e8d427-558c-4075-ab20-cd0e80a4a78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>7fc592a9-47a2-474f-b13d-1c42a91a69b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[2]/button</value>
      <webElementGuid>7a4c4d32-0c9c-4825-b264-16a6dc1357de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_6271' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>5a7e45f1-40fb-4927-89f7-dc062b02b5b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
