<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Product Out of stock</name>
   <tag></tag>
   <elementGuidId>3f0c8d76-d446-4f6f-a0a4-de614ab486d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.product-stock-message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='category_product']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>95cc34bc-13db-465d-9144-310bee92acf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-stock-message</value>
      <webElementGuid>ec7c2fd1-ad5e-4e06-99c6-59e7685ed956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product Out of stock</value>
      <webElementGuid>a07b9e8d-151f-4ce9-a5e1-5b75c0a42d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_product&quot;)/div[@class=&quot;product-box&quot;]/div[1]/div[@class=&quot;product-stock-message&quot;]</value>
      <webElementGuid>5ffd9550-f6f2-4a27-a6ce-da48edd1f004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_product']/div/div/div</value>
      <webElementGuid>3cabbd72-8fc5-4372-9933-d20d164fe82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='blackberry1'])[1]/following::div[1]</value>
      <webElementGuid>a7d632e8-2de2-4083-9df7-982b16cf1fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::div[5]</value>
      <webElementGuid>69b83510-e653-4e2c-93e0-ac0019242e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::div[1]</value>
      <webElementGuid>5a869bd0-53a2-45cf-8a96-46e123500d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::div[1]</value>
      <webElementGuid>bd6d2fb8-fc8c-495f-b9a2-81e54836d007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Product Out of stock']/parent::*</value>
      <webElementGuid>f4cb652d-2e6b-4f6a-81d6-f06ccc0dfeb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>4fc77565-3cad-4fc2-a92e-caf63e848693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Product Out of stock' or . = 'Product Out of stock')]</value>
      <webElementGuid>518b7eaa-548d-45b5-bd6b-ab3fd0cbba51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
