<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1edd7690-4f66-427c-92ed-0c7a9970afdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.vraj-login > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://www.vrajfresh.com/assets/images/user-icon.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6b52a61b-d508-4a6d-b5d0-ffa1fad828d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.vrajfresh.com/assets/images/user-icon.png</value>
      <webElementGuid>65d84092-6ad6-4fe5-befd-463c682185fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[1]/div[@class=&quot;container container-flex header&quot;]/div[@class=&quot;my-account&quot;]/ul[1]/li[@class=&quot;vraj-login&quot;]/a[1]/img[1]</value>
      <webElementGuid>8b95a743-3f08-4445-b0e2-13d473677551</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.vrajfresh.com/assets/images/user-icon.png')]</value>
      <webElementGuid>f13c0a63-23c5-47ad-90cd-eca02983946b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>6e146df8-d9c0-4d3f-82a2-4700c3e0ebb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.vrajfresh.com/assets/images/user-icon.png']</value>
      <webElementGuid>32a1903c-d294-4a49-a6bd-2095a8e00470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
