<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>17032ba1-4709-41cd-8974-2f8b6796757c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='popular-items']/div/div/div[4]/a/img)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0f608460-a988-4118-8c17-b028e427c311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.vrajfresh.com/admin/uploads/products/B58366DF-EB88-495D-89CC-4DA1475F00EF.jpg</value>
      <webElementGuid>6c24de2e-67dc-405f-a25b-43b16009b740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.src=&quot;https://www.vrajfresh.com/assets/images/logo-2.png&quot;</value>
      <webElementGuid>7708b4bb-02f8-4435-9ad2-36574f20687b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popular-product1&quot;)/div[@id=&quot;popular-items&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;product-box slick-slide slick-active&quot;]/a[1]/img[1]</value>
      <webElementGuid>48b8602d-dcd5-481d-82fe-e697f7bc9761</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='popular-items']/div/div/div[4]/a/img)[2]</value>
      <webElementGuid>33290c85-0c69-4af5-b4e5-7c638d193f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.vrajfresh.com/admin/uploads/products/B58366DF-EB88-495D-89CC-4DA1475F00EF.jpg')]</value>
      <webElementGuid>64dc09f5-a3e5-4622-bc5d-908cfbafc789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div/div/div/div/div/div[4]/a/img</value>
      <webElementGuid>cb59491f-471d-4a8a-9a86-fb29191fb47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.vrajfresh.com/admin/uploads/products/B58366DF-EB88-495D-89CC-4DA1475F00EF.jpg']</value>
      <webElementGuid>252dc95f-02a0-4306-a8be-34a9c9399ea3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
