<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Custom Tip_tip_amount</name>
   <tag></tag>
   <elementGuidId>310ced23-79cb-493a-8b93-7d2beffa6344</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tip_amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tip_amount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d91620b-f0bb-479c-bbd1-23de001eccfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Tip Amount</value>
      <webElementGuid>9301caad-6ca4-45a5-95aa-f52d34a681ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tip_amount</value>
      <webElementGuid>561840f1-7775-4e57-b411-0c0789793f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tip_amount</value>
      <webElementGuid>da8e7114-a7eb-4c98-9cad-66bd51a16220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>42841788-0d7c-4ca1-89c5-59e28e3e31e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isNumber(event)</value>
      <webElementGuid>6bfa75d4-618a-45ea-ba49-ed681e6164fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tip_amount&quot;)</value>
      <webElementGuid>6786505b-60c7-4202-8c4e-3140cc01aa21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tip_amount']</value>
      <webElementGuid>496cdf79-53f1-48f0-8082-1525aabe0d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/section/div/div/div[11]/input</value>
      <webElementGuid>9ff17e0d-daed-45e6-8ee9-7ee7e2a16c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>75b7c6ca-b362-4407-b72e-98e30f76c5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Tip Amount' and @name = 'tip_amount' and @id = 'tip_amount' and @type = 'text']</value>
      <webElementGuid>8c87ddae-2f1f-451f-9880-50de8ecb8b11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
