<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_0.4</name>
   <tag></tag>
   <elementGuidId>3726739a-495e-4c79-94c8-07ec47837c46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tbody:nth-of-type(2) > tr:nth-of-type(4) > td:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='State Tax'])[1]/following::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5d64812c-936d-46df-9e6c-c6e0d48bdce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$0.4</value>
      <webElementGuid>f1ebe6c0-60f6-4cc6-aea8-5e8e65aab46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;centered-content&quot;]/table[@class=&quot;no-spacing&quot;]/tbody[2]/tr[4]/td[2]</value>
      <webElementGuid>fd0bd6b2-aed1-4d79-8043-74c195ff2008</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State Tax'])[1]/following::td[1]</value>
      <webElementGuid>0736e94c-0121-41ce-8a8d-f72d29556b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[1]/following::td[2]</value>
      <webElementGuid>24d77d04-d554-4ff8-b989-6538a211e292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo Discount'])[1]/preceding::td[1]</value>
      <webElementGuid>df8fb347-b75e-406a-8510-7bde37d95a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$0.4']/parent::*</value>
      <webElementGuid>3f07b8e4-bc7d-4302-aac8-c72d77e9233f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[2]/tr[4]/td[2]</value>
      <webElementGuid>aac30b04-e13e-40d2-9816-79acf64a6335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '$0.4' or . = '$0.4')]</value>
      <webElementGuid>092e4e36-8775-4049-a5fe-a7c25cee2a87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
